```{r data}
data<-readxl::read_excel("C:/Users/animeshs/GD/Prediction analysis.xlsx", sheet=1)
data$Class<-"Remission"
data<-subset(as.data.frame(data), select = -c(1:7) )
summary(data)
```

```{r data2}
data2<-readxl::read_excel("C:/Users/animeshs/GD/Prediction analysis.xlsx", sheet=2)
data2$Class<-"Relapse"
data2<-subset(as.data.frame(data2), select = -c(1:7) )
summary(data2)
```

```{r data3}
data3<-readxl::read_excel("C:/Users/animeshs/GD/Prediction analysis.xlsx", sheet=3)
data3$Class<-"control"
data3<-subset(as.data.frame(data3), select = -c(1:2) )
summary(data3)
```

```{r data4}
data4<-readxl::read_excel("C:/Users/animeshs/GD/Prediction analysis.xlsx", sheet=4)
data4$Class<-"Active"
data4<-subset(as.data.frame(data4), select = -c(1:6) )
summary(data4)
```

```{r data5}
data5<-readxl::read_excel("C:/Users/animeshs/GD/Prediction analysis.xlsx", sheet=5)
data5$Class<-"ND"
data5<-subset(as.data.frame(data5), select = -c(1:7) )
summary(data5)
```

```{r merge}
dataM<-rbind(data,data2)
dataM<-rbind(dataM,data3)
dataM<-rbind(dataM,data4)
dataM<-rbind(dataM,data5)
write.csv(dataM,"C:/Users/animeshs/GD/Prediction analysis.merged_class.csv",row.names = F)
```

```{r p.value.2p}
install.pa(readxl)
ayurP<-read_excel("F:/promec/Animesh/HeLa/ayu/new/P value 0.02.xlsx", sheet=1)
summary(ayurP)
```
```{r p.value.2p}
ayurP<-read.csv("F:/promec/Animesh/HeLa/ayu/new/P value 0.02.csv")
summary(ayurP)
```

Cluster:https://cran.r-project.org/web/packages/umap/vignettes/umap.html

```{r umap}
#install.packages("umap")
library("umap")
dim(yyt)
#yytumap<-umap(yyt[,-58])
yyt.data<-yyt[,-12]
yyt.label<-yyt[,12]

yyt.umap<-umap(yyt.data)

yytumap$data
head(yyt.umap$layout)

plot.umap = function(x, labels,
         main="A UMAP visualization of the Iris dataset",
         colors=c("#ff7f00", "#e377c2", "#17becf"),
         pad=0.1, cex=0.65, pch=19, add=FALSE, legend.suffix="",
         cex.main=1, cex.legend=1) {
  layout = x
  if (class(x)=="umap") {
    layout = x$layout
  }

  xylim = range(layout)
  xylim = xylim + ((xylim[2]-xylim[1])*pad)*c(-0.5, 0.5)
  if (!add) {
    par(mar=c(0.2,0.7,1.2,0.7), ps=10)
    plot(xylim, xylim, type="n", axes=F, frame=F)
    rect(xylim[1], xylim[1], xylim[2], xylim[2], border="#aaaaaa", lwd=0.25)
  }
  points(layout[,1], layout[,2], col=colors[as.integer(labels)],
         cex=cex, pch=pch)
  mtext(side=3, main, cex=cex.main)
  labels.u = unique(labels)
  legend.pos = "topright"
  legend.text = as.character(labels.u)
  if (add) {
    legend.pos = "bottomright"
    legend.text = paste(as.character(labels.u), legend.suffix)
  }
  legend(legend.pos, legend=legend.text,
         col=colors[as.integer(labels.u)],
         bty="n", pch=pch, cex=cex.legend)
}
set.seed(123456)
#https://github.com/tkonopka/umap/blob/master/vignettes/umap.Rmd
plot.umap(yyt.umap,yyt.label)
```


ML:

```{r }
#install.packages("randomForest")
library(randomForest)
set.seed(100)
labelRF<-as.data.frame(label$Ayur)
rownames(labelRF)<-label$Name
#yyt<-as.data.frame(t(y$data))
yyt<-as.data.frame(t(y))
rownames(yyt)=sub("X.","",rownames(yyt))
rownames(yyt)=sub("\\..*","",rownames(yyt))
yyt[is.na(yyt)]<-0
summary(yyt)

yyt<-merge(yyt,labelRF,by=0, all=TRUE)
yyt<-yyt[,-1]
names(yyt)<- gsub(" ", "_", names(yyt))
names(yyt)<- gsub("-", "__", names(yyt))
yyt<-ayurP
summary(yyt)
#random_forest=randomForest(data=yyt,yyt$`label$Ayur`~.,impurity='gini',ntree=150,replace=TRUE)
random_forest=randomForest::randomForest(data=dataM,dataM$Class~.,ntree=500,replace=TRUE,proximity = TRUE)
print(random_forest)

plot(random_forest)
legend("top",cex=0.8,legend=colnames(random_forest$err.rate),lty=c(1,2,3),col=c(1,2,3),horiz=T)

sort(importance(random_forest))
varImpPlot(random_forest)
#qplot(RCN1,GALNT2,data=yyt,colour=class,size=I(3))
```



```{r p.value.100p}
ayurP<-read.table("F:/promec/Animesh/HeLa/ayu/new/Total Phylum.txt",header=T,sep="\t",row.names = 1)
summary(ayurP)
ayurP<-ayurP[2:20]
ayurP[is.na(ayurP)]<-0
library(pheatmap)
pheatmap(ayurP,scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
```

```{r label}
label<-read.table("F:/promec/Animesh/HeLa/ayu/new/class.txt",comment="D",header=T,sep="\t")
label$Name=sub("-2","",label$Name)
rownames(label)=label$Name
summary(label)
```

```{r data1}
y=log2(ayurP+1)
y[is.na(y)]<-0
library(robustscale)
y=robustscale(y)
names(y$data)=sub("X\\.","",names(y$data))
names(y$data)=sub("\\..*","",names(y$data))
summary(y$data)
colnames(y$data)
pheatmap(y$data,scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
pheatmap(y$data,scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",annotation_col = label)
```

```{r datacom}
y<-read.table(paste(pathD,toupper(typeF),"total",".txt",sep = ""),sep = "\t",header = T)
library(quantable)
row.names(y)<-y[,1]
y<-y[,-1]
summary(y)
y=merge(ayurP,y,by=0,all = TRUE)
row.names(y)<-y[,1]
y<-y[,-1]
y=robustscale(y)
y$data[is.na(y$data)]<-0
names(y$data)=sub("X","",names(y$data))
pheatmap(y$data,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,fontsize_col=6)
```

Scale:

```{r scale}
y<-read.table(paste(pathD,toupper(typeF),"total",".txt",sep = ""),sep = "\t",header = T)
#install.packages('quantable')
library(quantable)
row.names(y)<-y[,1]
y<-y[,-1]
#y<-as.matrix(unlist(y))
#y[is.na(y)]<-0
summary(y)
typeof(y)
y=robustscale(y)
y$data[is.na(y$data)]<-0
names(y$data)=sub("X","",names(y$data))
pheatmap(y$data,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6)
```


```{r}
otu <- read.csv("F:/promec/Results/Ani/Ayur/datanormalizationforotutable/Copy of OTU table.csv", stringsAsFactors=F)
species <- read.csv("C:/Users/animeshs/OneDrive - NTNU/ayurveda/species_div.csv",stringsAsFactors=T)
species <- read.csv("C:/Users/animeshs/OneDrive - NTNU/ayurveda/species_div_zscore_med.csv",stringsAsFactors=T)
summary(species$Species)
species$Escherichia.coli.K12
```


```{r}
library(rpart)
fit <- rpart(formula= Species ~ Eubacterium.rectale.ATCC.33656  + Dorea.longicatena.DSM.13814  + Prevotella.maculosa.OT.289 + Helicobacter.pullorum.MIT.98.5489 ,method="class", data=species,  control = rpart.control(cp = 1e-04))
fit <- rpart(Species ~ ., data=species, method="class", minsplit=2, minbucket=1)
fit <- rpart(Species ~ Eubacterium.rectale.ATCC.33656  + Escherichia.coli.K12+ Prevotella.maculosa.OT.289 + Helicobacter.pullorum.MIT.98.5489, data=species, method="class", minsplit=2, minbucket=1)
fit <- rpart(Species ~ Eubacterium.rectale.ATCC.33656  + Prevotella.maculosa.OT.289 , data=species, method="class", minsplit=2, minbucket=1)
printcp(fit)
plotcp(fit)
summary(fit)
plot(fit)
text(fit, use.n=TRUE, all=TRUE, cex=.6)
jpeg(fit, file = "C:/Users/animeshs/OneDrive - NTNU/ayurveda/tree.jpg")
pdf(fit, file = "C:/Users/animeshs/OneDrive - NTNU/ayurveda/tree.pdf")
prp(fit)
plot(1)
```

Plots:

```{r}
otu[1,]
plot(otu[,2])
hist(log2(otu[,2]))
```

Tree:

```{r, echo=FALSE}
#install.packages('party')
library(party)
k2p <- cforest( Kapha ~ Pita , data= otu, control=cforest_unbiased(mtry=2,ntree=50)) # fit the random forest
varimp(k2p)

```

#Source <http://rmarkdown.rstudio.com>  **Knit** button for HTML:
#https://peerj.com/preprints/1466.pdf
#http://marianattestad.com/blog/
#http://r-statistics.co/Variable-Selection-and-Importance-With-R.html
---
title: "Ayur"
author: "Ani"
date: "Friday, January 08, 2016"
output: html_document
---
