```{r data}
#inpF<-"L:/promec/Animesh/HeLa/ayu/new/Total Phylum.txt"
inpF<-"L:/promec/Animesh/HeLa/ayu/new/ayucombine species.txt"
data<-read.table(inpF,header=T,sep="\t",row.names = 1)
summary(data)
```

```{r heatmap}
#install.packages('pheatmap')
library(pheatmap)
y<-data[1:19]
summary(y)
pheatmap(y,scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
y[is.na(y)]<-0
pheatmap(y,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
```

```{r label}
inpL<-"L:/promec/Animesh/HeLa/ayu/new/class.txt"
label<-read.table(inpL,header=T,row.names=1,sep="\t")
colnames(label)
summary(label)
```

```{r scale}
#install.packages('quantable')
library(quantable)
y<-data[1:19]
y=robustscale(y)
y$data[is.na(y$data)]<-0
#pheatmap(y$data,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
names(y$data)=sub("X\\.","",names(y$data))
names(y$data)=sub("\\..*","",names(y$data))
pheatmap(y$data,scale="row",annotation_col = label, clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=2)
```

```{r scale}
#install.packages('quantable')
library(quantable)
yrs<-data[1:19]
#yrs<-yrs[rowSums(!is.na(yrs))>9,]
#yrs<-yrs[rowSums(!is.na(yrs))>14,]
yrs<-yrs[rowSums(!is.na(yrs))>18,]
yrs=robustscale(yrs)
yrs$data[is.na(yrs$data)]<-0
names(yrs$data)=sub("X\\.","",names(yrs$data))
names(yrs$data)=sub("\\..*","",names(yr
                                     
                                     
                                     
                                     
                                     s$data))
pheatmap(yrs$data,scale="row",annotation_col = label, clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=2)
```


```{r write}
#install.packages('dplyr')
library(dplyr)
colnames(y$data)
labelT=t(label)
colnames(labelT)=sub("\\-[0-9]+","",colnames(labelT))
yy<-rbind(y$data,labelT)
yy<-t(yy)
write.csv(yy,"L:/promec/Animesh/HeLa/ayu/new/ayucombine species.csv")
write.tab(t(yy),"L:/promec/Animesh/HeLa/ayu/new/ayucombine species.csv.txt")
```

```{r median}
yyy=read.csv("L:/promec/Animesh/HeLa/ayu/new/combined biological function.csv")
yyy=aggregate(. ~ Ayur, yyy,median)
row.names(yyy)=yyy[,1]
pheatmap(yyy[,3:30],scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
write.csv(yyy,"L:/promec/Animesh/HeLa/ayu/new/combined biological function median.csv")
#write.csv(yy,"L:/promec/Animesh/HeLa/ayu/new/Total Phylum.csv")
```

```{r install}
install.packages('gplots')
library(gplots) 
install.packages('MCMCglmm')
library(MCMCglmm)
install.packages('quantable')
library(quantable)
heatmap.2(as.matrix(log2(data[,3:10])))
log2data=data
log2data[is.na(log2data)]<-0
log2data<-(data[,3:21])
log2data<-log2(data[,3:21]+1)
rtnorm(n = 1, mean = mean(log2(data[!is.na(data),3:21])), sd = 1, lower = -Inf, upper = Inf)
data[is.na(data)]
plot(log2data)
names(data)  
#sub("(\\.*"([Ss][0-9]+)(\\.*)","\\2",names(data)) 
names(log2data)=sub("X\\.","",names(log2data))
names(log2data)=sub("\\..*","",names(log2data))
heatmap.2(as.matrix(log2data))
heatmap.2(as.matrix((log2data)),scale="row",col=redgreen, trace="none", tracecol="grey")
y=as.matrix((log2data))
y[is.na(y)]<-0
y=robustscale(y)
y=y$data
hr <- hclust(as.dist(1-cor(t(y), method="spearman")), method="complete") 
hc <- hclust(as.dist(1-cor(y, method="spearman")), method="complete")
heatmap(y, Rowv=as.dendrogram(hr), Colv=as.dendrogram(hc)) 
heatmap.2(y, Rowv=as.dendrogram(hr), Colv=as.dendrogram(hc),scale="row",col=redgreen, trace="none", tracecol="grey")
```



```{r check}
??auth
auth.MGRAST('MgRastWebKeyGoesHereKEJ88')
biom_phylum <- biomRequest(metadata("mgp80869")$mgp80869, request="organism", hit_type="all", source="RDP", group_level="phylum", evalue=15,  wait=TRUE)
phylum_matrix <- as.matrix(biom_phylum)
#biomRequest(file="Z:\\USERS\\ayurveda\\mgm4804295.3.csv",group_level="level2",evalue=1,)
```
```{r matR}
#https://github.com/MG-RAST/matR/blob/master/demo/simple.R
zz0 <- transform (zz, t_Log)
columns (zz0, "host_common_name|samp_store_temp|material")
princomp (zz0, map=c(col="host_common_name", pch="samp_store_temp"), labels="$$pubmed_id", cex=2)
distx (zz0, groups="$$host_common_name")
pp <- (rowstats (zz0, groups="$$material") $ p.value < 0.05)
pp[is.na(pp)] <- FALSE
pp

####  that information can be used to make an informative heatmap.

image (zz0 [pp,], margins=c(5,10), cexRow=0.3)

####  for comparison, here is the same heatmap, but including all annotations.

image (zz0, margins=c(5,10), cexRow=0.3)
```

```{r data}
http://api.metagenomics.anl.gov/m5nr/taxonomy?filter=Bacteroidetes&filter_level=phylum&min_level=genus

#install.packages('jsonlite')
library(jsonlite)
S5 <- fromJSON("http://api.metagenomics.anl.gov/1/annotation/sequence/mgm4804308.3?evalue=10&type=organism&source=SwissProt&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk")
head(S5)

#S5-mgm4804308.3
#http://api.metagenomics.anl.gov/1/annotation/sequence/mgm4804308.3?evalue=10&type=organism&source=SwissProt&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk
#s13_R2- https://api-ui.mg-rast.org/metagenome/72d6f57b296d676d343638363631342e33?verbosity=stats&detail=ontology&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk

#http://api.mg-rast.org/api.html#metagenome
#http://api.metagenomics.anl.gov/1/annotation/sequence/mmgm4804308.3?evalue=10&type=organism&source=SwissProt&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk

library(rjson)
S5 <- rjson::fromJSON(file="http://api.metagenomics.anl.gov/1/annotation/sequence/mgm4804308.3?evalue=10&type=organism&source=SwissProt&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk")
head(S5)

dAyu<-read.table('http://api.metagenomics.anl.gov/1/annotation/sequence/mgm4804308.3?evalue=10&type=organism&source=SwissProt&auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk',sep='')

http://api.metagenomics.anl.gov/metadata/export/mgp17042?auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk
http://api.metagenomics.anl.gov/project/mgp17042?auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk
http://api.metagenomics.anl.gov/inbox?auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk
http://api.metagenomics.anl.gov/sample/mgm4804308.3?auth=kbm2R6jxx9LSnLVNmtawtFBVtVNbk

https://www.mg-rast.org/mgmain.html?mgpage=project&project=760ca003346d67703137303432 
mgp17042

https://www.mg-rast.org/mgmain.html?mgpage=pipeline

Name    class   fwd     rev
s13     Vatta   TGGAACAA        TGGAACAA
S20-2   Pita    TGGCTTCA        TGGCTTCA
S23     Pita    TGGTGGTA        TGGTGGTA
S27     Kapha   TTCACGCA        TTCACGCA
S28     Vatta   AACTCACC        AACTCACC
S2      Kapha   TCCGTCTA        TCCGTCTA
S30     Kapha   AAGAGATC        AAGAGATC
S31     Kapha   AAGGACAC        AAGGACAC
S33     Kapha   AATCCGTC        AATCCGTC
S35     Vatta   AATGTTGC        AATGTTGC
S36     Vatta   ACACGACC        ACACGACC
S37     Pita    ACAGATTC        ACAGATTC
S3      Vatta   TCTTCACA        TCTTCACA
S40     Kapha   AGATGTAC        AGATGTAC
S44     Vatta   AGCACCTC        AGCACCTC
S46     Kapha   AGCCATGC        AGCCATGC
S47     Vatta   AGGCTAAC        AGGCTAAC
S48     Vatta   ATAGCGAC        ATAGCGAC
S5      Pita    TGAAGAGA        TGAAGAGA


system("mkdir ~/R/")
system("mkdir ~/R/libs/")


system("echo 'R_LIBS_USER=\"~/R/library\"' >  $HOME/.Renviron")

install.packages('devtools',lib.loc="/home/notebook/R/library")
install.packages('devtools')

```


