```{r data, echo = FALSE}
inpDr <-"F:/promec/Elite/LARS/2018/november/Rolf final/Red/combined/txt/"
inpDw <-"F:/promec/Elite/LARS/2018/november/Rolf final/White/combined/txt/"
dataR <- read.delim(paste0(inpDr,"proteinGroups.txt"),row.names=1,sep="\t",header = T)
dataW <- read.delim(paste0(inpDw,"proteinGroups.txt"),row.names=1,sep="\t",header = T)
data=merge(dataR,dataW,by=0,all=TRUE)
dim(data)
data$Row.names[1]
```

```{r clean, echo = FALSE}
decoyPrefix="REV__"
dataClean<-data[-grep(decoyPrefix, data$Row.names),]
contaminantPrefix="CON__"
dataClean<-dataClean[-grep(contaminantPrefix, dataClean$Row.names),]
summary(dataClean)
```


```{r select, echo = FALSE}
hdr="Fraction."
dataFrac=dataClean[,grep(hdr, names(dataClean))]
summary(dataFrac)
hist(as.matrix(dataFrac))
```

```{r imputeFilter0, echo = FALSE}
dataFrac[is.na(dataFrac)]<-0
summary(dataFrac)
```

```{r PCA, echo = FALSE}
plot(princomp(dataFrac))
biplot(prcomp(as.matrix(t(dataFrac)),scale = T))
biplot(prcomp(dataFrac,scale = T),col=c(1,8), cex=c(0.5, 0.4))
biplot(prcomp(as.matrix((dataFrac)),scale = T))
biplot(prcomp(t(dataFrac),scale = T),col=c(1,8), cex=c(0.5, 0.4))
```

```{r fraction-clust-plot, echo = FALSE}
#install.packages('pheatmap')
library(pheatmap)
dsub=data[(grepl("apo",data$Fasta.headers.x))|(grepl("alb",data$Fasta.headers.x))|(grepl("apo",data$Fasta.headers.y))|(grepl("alb",data$Fasta.headers.y)),]
rn<-strsplit(dsub$Row.names, ';')
y<-as.matrix(dsub[,grepl("Fraction\\.[0-9]+",colnames(dsub))])
row.names(y)<-paste(sapply(rn, "[", 1),sapply(rn, "[", 3),sapply(rn, "[", 6))
summary(y)
y[is.na(y)]<-0
summary(y)
svgPHC<-pheatmap(y,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE)#,annotation_col = label,show_rownames=F)
plot(svgPHC)
library(ggplot2)
ggsave(file=paste0(inpDr,hdr,"clusterPlot.svg"),plot=svgPHC)#,  width=6, height=6)
```

```{r selectX, echo = FALSE}
hdr=".x"
dataFracX=y[,grep(hdr, colnames(y))]
summary(dataFracX)
hist(as.matrix(dataFracX))
```

```{r selectY, echo = FALSE}
hdr=".y"
dataFracY=y[,grep(hdr, colnames(y))]
summary(dataFracY)
hist(as.matrix(dataFracY))
```

```{r XdY, echo = FALSE}
#xDy<-log2(dataFracX+1)-log2(dataFracY+1)
xDy<-dataFracX-dataFracY
#xDy<-dataFracX/dataFracY
hist(as.matrix(xDy))
svgPHC<-pheatmap(xDy,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE)#,annotation_col = label,show_rownames=F)
plot(svgPHC)
ggsave(file=paste0(inpDr,hdr,"xDy.clusterPlot.svg"),plot=svgPHC)#,  width=6, height=6)

```

```{r XpY, echo = FALSE}
xPy<-dataFracX+dataFracY
hist(as.matrix(xPy))
svgPHC<-pheatmap(xPy,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE)#,annotation_col = label,show_rownames=F)
plot(svgPHC)
ggsave(file=paste0(inpDr,hdr,"xPy.clusterPlot.svg"),plot=svgPHC)#,  width=6, height=6)

```


```{r dataC, echo = FALSE}
inpD <-"F:/promec/Elite/LARS/2018/november/Rolf final/txt/"
data0 <- read.delim(paste0(inpD,"proteinGroups.txt"),row.names=1,sep="\t",header = T)
dataC=merge(data0,data,by=0,all=TRUE)
```


```{r dataC, echo = FALSE}
dsub=dataC[(grepl("apo",dataC$Fasta.headers))|(grepl("alb",dataC$Fasta.headers))|(grepl("apo",dataC$Fasta.headers.x))|(grepl("alb",dataC$Fasta.headers.x))|(grepl("apo",dataC$Fasta.headers.y))|(grepl("alb",dataC$Fasta.headers.y)),]
rn<-strsplit(dsub$Row.names, ';')
y<-as.matrix(dsub[,grepl("Fraction\\.[0-9]+",colnames(dsub))])
row.names(y)<-paste(sapply(rn, "[", 1),sapply(rn, "[", 3),sapply(rn, "[", 6))
summary(y)
y[is.na(y)]<-0
summary(y)
svgPHC<-pheatmap(y,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE)#,annotation_col = label,show_rownames=F)
plot(svgPHC)

#dataC=merge(dataCR,dataCW,by=0,all=TRUE)
#dim(dataC)
#dataC$Row.names[1]
```

