data<-read.table("F:/OneDrive - NTNU/Desktop/combined/txt/proteinGroups.txt",header=T,sep="\t",row.names=1)
print(colnames(data))
log2SILAC<-log2(data[,grep("Ratio.H.L.normalized.",colnames(data))])
summary(log2SILAC)
log2SILAC[is.na(log2SILAC)]=0
summary(log2SILAC)
pValTT = apply(log2SILAC, 1, function(x) t.test(as.numeric(x))$p.value)
summary(pValTT)
pValTTcorrected = p.adjust(pValTT,method = "BH")
summary(pValTTcorrected)
log2median=apply(log2SILAC,1,function(x) median(x))
summary(log2median)
ttest.results = data.frame(Gene=data$Gene.names,Fasta=data$Fasta.headers,pValue=pValTT,pValTTcorrected=pValTTcorrected,Log2MedianChange=log2median)
summary(ttest.results)
write.csv(ttest.results,"F:/OneDrive - NTNU/Desktop/combined/txt/proteinGroups.csv",row.names = T)
select=(ttest.results$pValue<0.01)&(abs(ttest.results$Log2MedianChange)>1)&(ttest.results$Gene!="")
summary(select)
ttest.results.selected <- subset(ttest.results,select)
summary(ttest.results.selected)
write.csv(ttest.results.selected,"F:/OneDrive - NTNU/Desktop/combined/txt/proteinGroupsSelected.csv",row.names = T)
