#install.packages("BiocManager")
#BiocManager::install("limma")
#BiocManager::install("edgeR")
library(limma)
library(edgeR)
inpD<-"F:/OneDrive - NTNU/TK/mergeHISAT/subread.1697973662.results/"
inpF<-"Homo_sapiens.GRCh38.110.30.count.txt"
countTable = read.table(paste0(inpD,inpF),header=TRUE,row.names=1)
colnames(countTable)
countTableSel=countTable[,grep("TK",colnames(countTable))]
colnames(countTableSel)
colnames(countTableSel)=gsub("X.cluster.projects.nn9036k.scripts.TK.mergeHISAT.","",colnames(countTableSel))
colnames(countTableSel)
colnames(countTableSel)=gsub(".sort.bam","",colnames(countTableSel))
colnames(countTableSel)
boxplot(countTableSel)
countTableNorm=limma::voom(countTableSel, design = NULL, lib.size = NULL, normalize.method = "quantile",block = NULL, correlation = NULL, weights = NULL,span = 0.5, plot = FALSE, save.plot = FALSE)
countTableSelLog2=log2(countTableSel)
boxplot(countTableSelLog2)
countTableSelNorm=limma::voom(countTableSel, design = NULL, lib.size = NULL, normalize.method = "quantile",block = NULL, correlation = NULL, weights = NULL,span = 0.5, plot = FALSE, save.plot = FALSE)
range(log2(countTableNorm[["E"]]),na.rm=T)
hist(countTableSelNorm[["E"]])
boxplot(countTableSelNorm[["E"]])
countTableSelNormElog2=log2(countTableSelNorm[["E"]])
boxplot(countTableSelNormElog2)
hist(countTableSelNormElog2)
write.csv(countTableSelNormElog2,paste0(inpD,inpF,".countTableSelNormElog2.csv"))
hist(log(countTableSelNorm[["E"]]))
hist(countTableSelNorm[["weights"]])
condition = factor( c("Mut","Mut","WT","Mut","WT","WT"))
des = model.matrix(~-1+condition)
colnames(des) = levels(condition)
cmat <- makeContrasts(WT - Mut, levels=des)
dge <- DGEList(counts=countTable)
dge <- calcNormFactors(dge)
v <- voom(dge,design=des)
fit <- lmFit(v,design=des)
fit <- contrasts.fit(fit, cmat)
fit <- eBayes(fit)
a <- decideTests(fit,adjust.method="fdr", p.value=0.05, lfc=0)
sma = summary(a)
dmm <- dim(countTable)
res <- topTable(fit,n=dmm[1],coef=1)
plot(res$logFC,-log10(res$adj.P.Val))
write.csv(res,file=paste0(inpD,"Voom_diffexp.csv"))
