```{r data, echo = FALSE}
inpD <-"L:/promec/Animesh/Lisa/"
inpF<-paste0(inpD,"CamillaWSRTdataMedianUniprotGOmin2pv25p.txt")
data <- read.delim(inpF,sep="\t",header = T)
#data <- read.delim(paste0(inpD,"CamillaWSRTdataMedian.txt"),sep="\t",header = T)
rownames(data)<-paste(data$T..T..Uniprot,data$T..T..Line,data$T..T..Gene.names,sep = ";")
summary(data)
```

```{r data-mapped}
selThr<-0.3
inpD <-"L:/promec/Animesh/Lisa/"
inpF<-paste0(inpD,"CamillaWSRTdataMedianUniprotGOmin2pv25p.txt")
inpO<-paste0(inpF,"Mapped-MCCAR-NB4-MO.csv")
dataSezWP <- read.csv(inpO,row.names = 1)
summary(dataSezWP)
inpOm<-paste0(inpF,"MappedSel.csv")
write.csv(cbind(dataSezWP[,c(3:32,68)],rownames(dataSezWP)),inpOm,row.names = F)
```

```{r data-jinxian}
selThr<-0.3
inpD <-"L:/promec/Animesh/Lisa/"
inpJ<-paste0(inpD,"jinxian_t1.xlsx")
#install.packages("readxl")
dataSezJX <- readxl::read_xlsx(inpJ)
summary(dataSezJX)
GeneJL<-dataSezJX[!is.na(dataSezJX$`Metabolite or enzyme`),1]
GeneJL<-GeneJL[c(13:25),]
#https://en.wikipedia.org/wiki/Oxoglutarate_dehydrogenase_complex
GeneJL[10,]<-c("OGDH,DLST,DLD")
#https://stackoverflow.com/a/15347463
s <- strsplit(GeneJL$`Metabolite or enzyme`, split = " ")
s <- strsplit(unlist(s), split = ",")
GeneJL<-data.frame(gene=toupper(unlist(s)))
write.csv(GeneJL,paste0(inpJ,"GeneJL.csv"),row.names = F)
```

```{r dataSezJX, echo = FALSE}
dataSel <- dataSezWP[,c(3:32,68)]
geneN<-toupper(sapply(strsplit(row.names(dataSel),";"), `[`, 1))
dataSel<-cbind.data.frame(dataSel,geneN)
dataSel<-merge(GeneJL,dataSel,by.y="geneN",by.x="gene",all.x = T)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="dataSezJX",counts.col = "red")
rn<-dataSel$gene
gn<-1:nrow(dataSel)
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste(rn,gn,"_JX",sep=";")
dataSelJX<-dataSel
summary(dataSelJX)
```

```{r dataSezJX-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelJX
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
#https://stackoverflow.com/a/18055983
data_selr<-data_selr[apply(data_selr[,-1], 1, function(x) !all(x==0)),]
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#install.packages("scales")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelJX.svg"),plot=svgPHC)#,  
```

```{r limma::vennDiagram}
selThr<-0.3
dataV<-data[,c(1,2,3,6)]
#dataV<-data[(data$B_.WSRT<selThr),]
hist((as.matrix(dataV)))
#hist(rowSums(as.matrix(dataV)))
#library(eulerr)
#euler(dataV<selThr)$original.values
#https://stats.idre.ucla.edu/r/faq/how-can-i-generate-a-venn-diagram-in-r/
#install.packages("BiocManager")
#BiocManager::install("limma")
#library(limma)
limma::vennDiagram(dataV<selThr)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpF,"venn.svg"),plot=limma::vennDiagram(dataV<selThr))#,  width=6, height=6)
```

```{r sel-WSRT-onevar-in3}
selThr<-0.3
dataS<-data[(data$ONO_.WSRT<selThr) | (data$CCAR_.WSRT<selThr) | (data$NB_.WSRT<selThr),]
hist(rowSums(as.matrix(dataS[,c(1,2,3,6)])))
limma::vennDiagram(dataS[,c(1,2,3,6)]<selThr)
```

```{r sel-WSRT-onevar}
selThr<-0.3
dataS<-data[(data$ONO_.WSRT<selThr) | (data$B_.WSRT<selThr) | (data$CCAR_.WSRT<selThr) | (data$NB_.WSRT<selThr),]
hist(rowSums(as.matrix(dataS[,c(1,2,3,6)])))
limma::vennDiagram(dataS[,c(1,2,3,6)]<selThr)
```

```{r sel-WSRT-twovar}
dataS<-data[(data$ONO_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$ONO_.WSRT<selThr & data$B_.WSRT<selThr) | (data$B_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$ONO_.WSRT<selThr & data$NB_.WSRT<selThr) | (data$NB_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$NB_.WSRT<selThr & data$B_.WSRT<selThr) ,]
hist(rowSums(as.matrix(dataS[,c(1,2,3,6)])))
limma::vennDiagram(dataS[,c(1,2,3,6)]<selThr)
```

```{r map-ID}
#BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)
uniP<-c("P07237","P28331","Q12931")
select(org.Hs.eg.db, uniP, "ENTREZID", "UNIPROT")
#BiocManager::install("clusterProfiler")
#library(clusterProfiler)
#http://data.wikipathways.org/current/gmt/
#wp2gene <- clusterProfiler::read.gmt("L:/promec/Animesh/Lisa/wikipathways-20191010-gmt-Homo_sapiens.gmt")
wp2gene <- clusterProfiler::read.gmt("L:/promec/Animesh/Lisa/wikipathways-20201010-gmt-Homo_sapiens.gmt")
library(magrittr)
wp2gene <- wp2gene %>% tidyr::separate(term, c("name","version","wpid","org"), "%")
wpid2gene <- wp2gene %>% dplyr::select(wpid, gene) #TERM2GENE
wpid2name <- wp2gene %>% dplyr::select(wpid, name) #TERM2NAME
wpid2name[grep("apoptosis",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("stat",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("mapk",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("akt",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("mtor",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("pi3k",wpid2name$name,ignore.case = TRUE),]
#select(org.Hs.eg.db, uniP, "GENENAME", "UNIPROT")
#select(org.Hs.eg.db, uniP, "SYMBOL", "UNIPROT")
uniP<-data$T..Uniprot
uniP <- lapply(uniP, as.character)
unlist(uniP)
uniP[[1]]
uniL<-select(org.Hs.eg.db, unlist(uniP), "ENTREZID", "UNIPROT")
wpid2gene[grep(uniL$ENTREZID[1],wpid2gene$gene,ignore.case = TRUE),]
wpid2gene[grep("361",wpid2gene$gene,ignore.case = TRUE),]
uniprots <- Rkeys(org.Hs.egUNIPROT)
uniprots2entrez <- select(org.Hs.eg.db, uniprots, "ENTREZID", "UNIPROT")
dataSez<-merge(dataS, uniprots2entrez, by.x="T..Uniprot", by.y="UNIPROT")
dataSez<-merge(dataS, uniprots2entrez, by.x="T..Entry", by.y="UNIPROT")
dataSezWP<-merge(dataSez, wp2gene, by.x="ENTREZID", by.y="gene")
#rownames(dataSezWP)<-paste(dataSezWP$T..T..Uniprot,dataSezWP$T..T..Line,dataSezWP$name,dataSezWP$ENTREZID,sep = "_")
rownames(dataSezWP)<-paste(dataSezWP$T..T..Gene.names,dataSezWP$T..T..Uniprot,dataSezWP$T..T..Line,dataSezWP$ENTREZID,dataSezWP$name,sep = ";")
reOrderCol<-
colnames(dataSezWP)[c(3,4,5,8)]<-colnames(dataSezWP)[c(8,4,5,3)]
dataSezWP[,c(3,4,5,8)]<-dataSezWP[,c(8,4,5,3)]
colnames(dataSezWP)<-sub("_.WSRT","W",colnames(dataSezWP))
#sapply(strsplit(colnames(dataSezWP),"_",fixed=TRUE),`[`, 1)
inpO<-paste0(inpF,"MappedJJN3-MCCAR-NB4-MO.csv")
write.csv(cbind(rownames(dataSezWP),dataSezWP),inpO,row.names = F)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
group<-"PI3K-Akt-mTOR"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Apoptosis, echo = FALSE}
group<-"Apoptosis"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
group<-"PI3K-Akt-mTOR"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Amino, echo = FALSE}
group<-"amino"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Glycolysis, echo = FALSE}
group<-"Glycolysis"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Lipids, echo = FALSE}
group<-"lipid"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Purine, echo = FALSE}
group<-"purine"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr=rbind(data_selr,MIN=rep(-3,ncol(data_selr)),MAX=rep(3,ncol(data_selr)))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r pyrimidine, echo = FALSE}
group<-"pyrimidine"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Nucleic, echo = FALSE}
group<-"nucleic"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r list-metabolism, echo = FALSE}
#install.packages("readxl")
listMetabo<-readxl::read_xlsx(paste0(inpD,"/Liste.xlsx"),col_names = F)
summary(listMetabo)
listMetabo$...1=gsub(" ", "", listMetabo$...1)
UniprotLM<-listMetabo#listMetabo[!is.na(listMetabo$...1),1]
s <- strsplit(UniprotLM$...1, split = ",")
UniprotLM<-data.frame(gene=sapply(s, "[", 1),protein=sapply(s, "[", 2))
UniprotLM$line=1:nrow(UniprotLM)
group<-""
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
dataSel<-merge(UniprotLM,dataSel,by.x="protein",by.y="pathwayN",all.x=T)
dataSel<-dataSel[order(dataSel$line),]
row.names(dataSel)<-dataSel$gene
dataSel<-dataSel[,-c(1)]
dataSel<-dataSel[,-c(1)]
dataSel<-dataSel[,-c(1)]
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
#assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=F,cluster_rows=F,color=my_palette,fontsize_col=6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r metabolism, echo = FALSE}
group<-"metabolism"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
group<-"PI3K-Akt-mTOR"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
group<-"PI3K-Akt-mTOR"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r mRNA Processing, echo = FALSE}
dataSel <- dataSezWP[grep("mRNA Processing", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_mRNAProcessing")
dataSelmRNAProcessing<-dataSel
summary(dataSelmRNAProcessing)
```

```{r dataSelmRNAProcessing-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelmRNAProcessing
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#install.packages("scales")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelmRNAProcessing.svg"),plot=svgPHC)#,  
```

```{r Histone Modifications, echo = FALSE}
dataSel <- dataSezWP[grep("Histone Modifications", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_HistoneModifications")
dataSelHistoneModifications<-dataSel
summary(dataSelHistoneModifications)
```

```{r dataSelHistoneModifications-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelHistoneModifications
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelHistoneModifications.svg"),plot=svgPHC)#,  
```

```{r Integrin-mediated Cell Adhesion, echo = FALSE}
dataSel <- dataSezWP[grep("Integrin-mediated Cell Adhesion", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_IntegrinCellAdhesion")
dataSelIntegrinCellAdhesion<-dataSel
summary(dataSelIntegrinCellAdhesion)
```

```{r dataSelIntegrinCellAdhesion-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelIntegrinCellAdhesion
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelIntegrinCellAdhesion.svg"),plot=svgPHC)#,  
```

```{r nucleic, echo = FALSE}
dataSel <- dataSezWP[grep("nucleic acid metabolism", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_nucleic")
dataSelNucleic<-dataSel
summary(dataSelNucleic)
```

```{r nucleic-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelNucleic
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelNucleic.svg"),plot=svgPHC)#,  
```

```{r purine, echo = FALSE}
dataSel <- dataSezWP[grep("purine metabolism", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_purine")
dataSelPurine<-dataSel
summary(dataSelPurine)
```

```{r purine-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelPurine
#install.packages("scales")
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap::pheatmap")
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelPurine.svg"),plot=svgPHC)#,  
```


```{r pyrimidine, echo = FALSE}
dataSel <- dataSezWP[grep("Pyrimidine", dataSezWP$name,ignore.case=TRUE),] 
#aggregate(. ~ x, transform(dataSel, x = rownames(dataSel)), sum)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="pyrimidine",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_pyrimidine")
dataSelPyrimidine<-dataSel
summary(dataSelPyrimidine)
```

```{r pyrimidine-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelPyrimidine
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.pyrimidine.svg"),plot=svgPHC)#,  
```

```{r lipid, echo = FALSE}
dataSel <- dataSezWP[grep("lipid", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="lipid",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_lipid")
dataSelLipid<-dataSel
summary(dataSelLipid)
```

```{r lipid-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelLipid
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelLipid.svg"),plot=svgPHC)#,  
```

```{r glycolysis, echo = FALSE}
dataSel <- dataSezWP[grep("glycolysis", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="glycolysis",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_glycolysis")
dataSelGlycolysis<-dataSel
summary(dataSelGlycolysis)
```

```{r glycolysis-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelGlycolysis
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.glycolysis.svg"),plot=svgPHC)#,  
```

```{r amino, echo = FALSE}
dataSel <- dataSezWP[grep("amino", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="amino",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_amino")
dataSelAmino<-dataSel
summary(dataSelAmino)
```

```{r amino-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelAmino
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.amino.svg"),plot=svgPHC)#,  
```

```{r metabolism, echo = FALSE}
dataSel <- dataSezWP[grep("stat", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_STAT")
dataSelSTAT<-dataSel
summary(dataSelSTAT)
```

```{r MAPK, echo = FALSE}
dataSel <- dataSezWP[grep("mapk", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="MAPK",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelMAPK.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="MAPK",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_MAPK")
dataSelMAPK<-dataSel
summary(dataSelMAPK)
write.csv(cbind(rownames(dataSelMAPK),dataSelMAPK),paste0(inpF,"MAPK.csv"),row.names = F)
```

```{r STAT, echo = FALSE}
dataSel <- dataSezWP[grep("stat", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelSTAT.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_STAT")
dataSelSTAT<-dataSel
summary(dataSelSTAT)
write.csv(cbind(rownames(dataSelSTAT),dataSelSTAT),paste0(inpF,"STAT.csv"),row.names = F)
```


```{r AMPK, echo = FALSE}
dataSel <- dataSezWP[grep("ampk", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="AMPK",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelAMPK.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="AMPK",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_AMPK")
dataSelAMPK<-dataSel
summary(dataSelAMPK)
write.csv(cbind(rownames(dataSelAMPK),dataSelAMPK),paste0(inpF,"AMPK.csv"),row.names = F)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
dataSelPI3K <- dataSezWP[(grep("PI3K", dataSezWP$name,ignore.case=TRUE)),]
dataSelAKT <- dataSezWP[(grep("AKT", dataSezWP$name,ignore.case=TRUE)),]
dataSelmTOR <- dataSezWP[(grep("mTOR", dataSezWP$name,ignore.case=TRUE)),] 
dataSel_PI3KAKTmTOR <- dataSezWP[(grep("PI3K-Akt-mTOR", dataSezWP$name,ignore.case=TRUE)),] 
#dataSel <- dataSezWP[(grep("AKT", dataSezWP$name,ignore.case=TRUE))|(grep("PI3K", dataSezWP$name,ignore.case=TRUE))|(grep("mTOR", dataSezWP$name,ignore.case=TRUE)),] 
dataSel<-dataSel_PI3KAKTmTOR#rbind(dataSelPI3K,dataSelAKT,dataSelmTOR)
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
#dataSel<-as.matrix(dataSel[,-13])
summary(dataSel)
#selThr<-0.6
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="PI3K-Akt-mTOR",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelPI3KAKTmTOR.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="PI3K-Akt-mTOR",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_PI3K-Akt-mTOR")
dataSel_PI3KAKTmTOR<-dataSel
summary(dataSel_PI3KAKTmTOR)
write.csv(cbind(rownames(dataSel_PI3KAKTmTOR),dataSel_PI3KAKTmTOR),paste0(inpF,"dataSel_PI3KAKTmTOR.csv"),row.names = F)
```

```{r Apoptosis, echo = FALSE}
dataSel <- dataSezWP[grep("apoptosis", dataSezWP$name,ignore.case=TRUE),]
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
#selThr<-0.3
#limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red")
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
#colnames(dataSel)<-sub("_W","W",colnames(dataSel))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelApoptisis.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#limma::vennDiagram(dataSel[,c(8,3,4,5)]<selThr,main="Apoptosis",counts.col = "red")
#data_apop <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_jak <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_mapk <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_jaks <- data[grep("jak", data$C..KEGG.name),] 
#data_mapk <- data[grep("mapk signaling pathway", data$C..KEGG.name),]
#data_selr <- data[grep("MAPK signaling pathway", data$C..KEGG.name),]
#data_selr<-rbind.data.frame(data_apop,data_apop,data_mapk)
rownames(dataSel)<-paste0(rownames(dataSel),"_Apopto")
dataSelApoptosis<-dataSel
summary(dataSelApoptosis)
write.csv(cbind(rownames(dataSelApoptosis),dataSelApoptosis),paste0(inpF,"Apoptosis.csv"),row.names = F)
```


```{r sel-data-cols, echo = FALSE}
data_selr_s<-rbind.data.frame(dataSelApoptosis)#,dataSelMAPK,dataSelSTAT,dataSelAMPK,dataSel_PI3KAKTmTOR)
#data_selr[data_selr==0]=NA
#install.packages("scales")
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
##library(quantable)
#data_selr_s=robustscale(data_selr,dim=1,center = FALSE)#,scale=TRUE,  preserveScale = FALSE)
#data_selr_s=data_selr_s$data
#data_selr$data[is.na(data_selr$data)]<-0
#y$data<-y$data[-(which(rowSums(y$data) == 0)),] 
#data_selr<-dataSel
#data_selr<-data_selr$data
#data_selr<-data_selr[-(which(rowSums(data_selr) == 0)),] 
summary(data_selr)
hist(as.matrix(data_selr))
#data_selr['pathwayN']<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
#data_selr=subset(data_selr, !duplicated(pathwayN))
#row.names(data_selr)=data_selr$pathwayN
data_selr<-as.matrix(data_selr[,-13])
#pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 5)
summary(data_selr)
#hist(as.matrix(data_selr))
#```

#```{r clust-plot, echo = FALSE}
#install.packages('pheatmap::pheatmap')
#library(pheatmap::pheatmap)
#?pheatmap::pheatmap
#rn<-sub(";","",data_selr$T..T..Gene.names)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
#data_selr[data_selr==0]=NA
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
#rn<-strsplit(rn, "apolipoprotein")
#rn<-strsplit(rn, " ")
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
#svgPHC<-pheatmap::pheatmap(y,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6)#,annotation_col = label,show_rownames=F)
#https://stackoverflow.com/a/44400007/1137129
bk1 <- c(seq(-1,-0.01,by=0.01))
bk2 <- c(seq(0.01,1,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#svgPHC<-pheatmap::pheatmap(data_selr,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,labels_row =  pathwayN,cluster_rows=TRUE,color = colorRampPalette(c( "navy", "white","firebrick"))(50),na_col = "grey")#,annotation_col = label,show_rownames=F)
#library(ggplot2)
#ggplot2::ggsave(file=paste0(inpF,"corrcoefED.svg"), plot=svgPHC, width=6, height=6)
#plot(svgPHC)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.ApoptoMAPKSTATAMPKPI3KAKTmTOR.svg"),plot=svgPHC)#,  width=6, height=6)
#ggplot2::ggsave(file=paste0(inpD,hdr,"clusterPlot.Apoptosis.svg"),plot=svgPHC)#,  width=6, height=6)
#ggplot2::ggsave(file=paste0(inpD,hdr,"clusterPlot.MAPK.svg"),plot=svgPHC)#,  width=6, height=6)
```

```{r apohc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelApoptosis
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.Apoptosis.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"ApoptosisHC.csv"),row.names = F)
```

```{r sel-data-cols, echo = FALSE}
data_selr_s<-dataSelApoptosis
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.Apoptosis.svg"),plot=svgPHC)#,  
```
```{r mapkhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelMAPK
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.MAPK.svg"),plot=svgPHC)#,  
```
```{r ampkhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelAMPK
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.AMPK.svg"),plot=svgPHC)#,  
```
```{r stathc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelSTAT
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.STAT.svg"),plot=svgPHC)#,  
```

```{r pi3kallhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSel_PI3KAKTmTOR
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.PI3Ketc.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"PI3KetcHC.csv"),row.names = F)
```

```{r sel-WSRT-twovar}
selThr<-0.3
dataS<-data[(data$ONO_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$ONO_.WSRT<selThr & data$B_.WSRT<selThr) | (data$B_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$ONO_.WSRT<selThr & data$NB_.WSRT<selThr) | (data$NB_.WSRT<selThr & data$CCAR_.WSRT<selThr) | (data$NB_.WSRT<selThr & data$B_.WSRT<selThr) ,]
hist(rowSums(as.matrix(dataS[,c(1,2,3,6)])))
limma::vennDiagram(dataS[,c(1,2,3,6)]<selThr)
```

```{r data-mapped}
selThr<-0.3
inpD <-"L:/promec/Animesh/Lisa/"
inpF<-paste0(inpD,"CamillaWSRTdataMedianUniprotGOmin2pv25p.txt")
inpO<-paste0(inpF,"MappedJJN3-MCCAR-NB4-MO-twovar.csv")
dataSezWP <- read.csv(inpO,row.names = 1)
summary(dataSezWP)
inpOm<-paste0(inpF,"MappedJJN3-MCCAR-NB4-MO-twovar-Select.csv")
write.csv(cbind(dataSezWP[,c(3:32,68)],rownames(dataSezWP)),inpOm,row.names = F)
```

```{r map-ID}
#BiocManager::install("org.Hs.eg.db")
library(org.Hs.eg.db)
uniP<-c("P07237","P28331","Q12931")
select(org.Hs.eg.db, uniP, "ENTREZID", "UNIPROT")
#BiocManager::install("clusterProfiler")
#library(clusterProfiler)
#http://data.wikipathways.org/current/gmt/
#wp2gene <- clusterProfiler::read.gmt("L:/promec/Animesh/Lisa/wikipathways-20191010-gmt-Homo_sapiens.gmt")
wp2gene <- clusterProfiler::read.gmt("L:/promec/Animesh/Lisa/wikipathways-20201010-gmt-Homo_sapiens.gmt")
library(magrittr)
wp2gene <- wp2gene %>% tidyr::separate(term, c("name","version","wpid","org"), "%")
wpid2gene <- wp2gene %>% dplyr::select(wpid, gene) #TERM2GENE
wpid2name <- wp2gene %>% dplyr::select(wpid, name) #TERM2NAME
wpid2name[grep("apoptosis",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("stat",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("mapk",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("akt",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("mtor",wpid2name$name,ignore.case = TRUE),]
wpid2name[grep("pi3k",wpid2name$name,ignore.case = TRUE),]
#select(org.Hs.eg.db, uniP, "GENENAME", "UNIPROT")
#select(org.Hs.eg.db, uniP, "SYMBOL", "UNIPROT")
uniP<-data$T..Uniprot
uniP <- lapply(uniP, as.character)
unlist(uniP)
uniP[[1]]
uniL<-select(org.Hs.eg.db, unlist(uniP), "ENTREZID", "UNIPROT")
wpid2gene[grep(uniL$ENTREZID[1],wpid2gene$gene,ignore.case = TRUE),]
wpid2gene[grep("361",wpid2gene$gene,ignore.case = TRUE),]
uniprots <- Rkeys(org.Hs.egUNIPROT)
uniprots2entrez <- select(org.Hs.eg.db, uniprots, "ENTREZID", "UNIPROT")
dataSez<-merge(dataS, uniprots2entrez, by.x="T..Uniprot", by.y="UNIPROT")
dataSez<-merge(dataS, uniprots2entrez, by.x="T..Entry", by.y="UNIPROT")
dataSezWP<-merge(dataSez, wp2gene, by.x="ENTREZID", by.y="gene")
#rownames(dataSezWP)<-paste(dataSezWP$T..T..Uniprot,dataSezWP$T..T..Line,dataSezWP$name,dataSezWP$ENTREZID,sep = "_")
rownames(dataSezWP)<-paste(dataSezWP$T..T..Gene.names,dataSezWP$T..T..Uniprot,dataSezWP$T..T..Line,dataSezWP$ENTREZID,dataSezWP$name,sep = ";")
reOrderCol<-
colnames(dataSezWP)[c(3,4,5,8)]<-colnames(dataSezWP)[c(8,4,5,3)]
dataSezWP[,c(3,4,5,8)]<-dataSezWP[,c(8,4,5,3)]
colnames(dataSezWP)<-sub("_.WSRT","W",colnames(dataSezWP))
#sapply(strsplit(colnames(dataSezWP),"_",fixed=TRUE),`[`, 1)
inpO<-paste0(inpF,"MappedJJN3-MCCAR-NB4-MO-twovar.csv")
write.csv(cbind(rownames(dataSezWP),dataSezWP),inpO,row.names = F)
```

```{r Amino, echo = FALSE}
group<-"amino"
groupData<-paste0(group,"_min2_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Glycolysis, echo = FALSE}
group<-"Glycolysis"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Lipids, echo = FALSE}
group<-"lipid"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Purine, echo = FALSE}
group<-"purine"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r pyrimidine, echo = FALSE}
group<-"pyrimidine"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r Nucleic, echo = FALSE}
group<-"nucleic"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r metabolism, echo = FALSE}
group<-"metabolism"
groupData<-paste0(group,"_data_selr")
dataSel <- dataSezWP[(grep(group, dataSezWP$name,ignore.case=TRUE)),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red")
ggplot2::ggsave(file=paste0(inpF,group,".vennPlot.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main=group,counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#rownames(dataSel)<-paste(rownames(dataSel),group,sep="_")
summary(dataSel)
write.csv(cbind(rownames(dataSel),dataSel),paste0(inpF,group,".dataSel.csv"),row.names = F)
assign(group,dataSel)
#install.packages("scales")
data_selr=scales::squish(as.matrix(dataSel),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap")
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=4,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize_col  = 4)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
ggplot2::ggsave(file=paste0(inpF,group,"clusterPlot.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,group,".data_selr.csv"),row.names = F)
assign(groupData,data_selr)
```

```{r mRNA Processing, echo = FALSE}
dataSel <- dataSezWP[grep("mRNA Processing", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_mRNAProcessing")
dataSelmRNAProcessing<-dataSel
summary(dataSelmRNAProcessing)
```

```{r dataSelmRNAProcessing-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelmRNAProcessing
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#install.packages("scales")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelmRNAProcessing.svg"),plot=svgPHC)#,  
```

```{r Histone Modifications, echo = FALSE}
dataSel <- dataSezWP[grep("Histone Modifications", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_HistoneModifications")
dataSelHistoneModifications<-dataSel
summary(dataSelHistoneModifications)
```

```{r dataSelHistoneModifications-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelHistoneModifications
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelHistoneModifications.svg"),plot=svgPHC)#,  
```

```{r Integrin-mediated Cell Adhesion, echo = FALSE}
dataSel <- dataSezWP[grep("Integrin-mediated Cell Adhesion", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_IntegrinCellAdhesion")
dataSelIntegrinCellAdhesion<-dataSel
summary(dataSelIntegrinCellAdhesion)
```

```{r dataSelIntegrinCellAdhesion-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelIntegrinCellAdhesion
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelIntegrinCellAdhesion.svg"),plot=svgPHC)#,  
```

```{r nucleic, echo = FALSE}
dataSel <- dataSezWP[grep("nucleic acid metabolism", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_nucleic")
dataSelNucleic<-dataSel
summary(dataSelNucleic)
```

```{r nucleic-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelNucleic
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#install.packages("ggplot2")
#install.packages("svglite")
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelNucleic.svg"),plot=svgPHC)#,  
```

```{r purine, echo = FALSE}
dataSel <- dataSezWP[grep("purine metabolism", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_purine")
dataSelPurine<-dataSel
summary(dataSelPurine)
```

```{r purine-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelPurine
#install.packages("scales")
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#install.packages("pheatmap::pheatmap")
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelPurine.svg"),plot=svgPHC)#,  
```


```{r pyrimidine, echo = FALSE}
dataSel <- dataSezWP[grep("Pyrimidine", dataSezWP$name,ignore.case=TRUE),] 
#aggregate(. ~ x, transform(dataSel, x = rownames(dataSel)), sum)
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="pyrimidine",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_pyrimidine")
dataSelPyrimidine<-dataSel
summary(dataSelPyrimidine)
```

```{r pyrimidine-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelPyrimidine
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.pyrimidine.svg"),plot=svgPHC)#,  
```

```{r lipid, echo = FALSE}
dataSel <- dataSezWP[grep("lipid", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="lipid",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_lipid")
dataSelLipid<-dataSel
summary(dataSelLipid)
```

```{r lipid-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelLipid
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.dataSelLipid.svg"),plot=svgPHC)#,  
```

```{r glycolysis, echo = FALSE}
dataSel <- dataSezWP[grep("glycolysis", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="glycolysis",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_glycolysis")
dataSelGlycolysis<-dataSel
summary(dataSelGlycolysis)
```

```{r glycolysis-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelGlycolysis
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.glycolysis.svg"),plot=svgPHC)#,  
```

```{r amino, echo = FALSE}
dataSel <- dataSezWP[grep("amino", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="amino",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_amino")
dataSelAmino<-dataSel
summary(dataSelAmino)
```

```{r amino-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelAmino
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),";"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.amino.svg"),plot=svgPHC)#,  
```

```{r metabolism, echo = FALSE}
dataSel <- dataSezWP[grep("stat", dataSezWP$name,ignore.case=TRUE),] 
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_STAT")
dataSelSTAT<-dataSel
summary(dataSelSTAT)
```

```{r MAPK, echo = FALSE}
dataSel <- dataSezWP[grep("mapk", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="MAPK",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelMAPK2sig.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="MAPK",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_MAPK")
dataSelMAPK<-dataSel
summary(dataSelMAPK)
write.csv(cbind(rownames(dataSelMAPK),dataSelMAPK),paste0(inpF,"MAPK2sig.csv"),row.names = F)
```

```{r STAT, echo = FALSE}
dataSel <- dataSezWP[grep("stat", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelSTAT2sig.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="STAT",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_STAT")
dataSelSTAT<-dataSel
summary(dataSelSTAT)
write.csv(cbind(rownames(dataSelSTAT),dataSelSTAT),paste0(inpF,"STAT2sig.csv"),row.names = F)
```


```{r AMPK, echo = FALSE}
dataSel <- dataSezWP[grep("ampk", dataSezWP$name,ignore.case=TRUE),] 
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="AMPK",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelAMPK2sig.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="AMPK",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_AMPK")
dataSelAMPK<-dataSel
summary(dataSelAMPK)
write.csv(cbind(rownames(dataSelAMPK),dataSelAMPK),paste0(inpF,"AMPK2sig.csv"),row.names = F)
```

```{r PI3K/AKT/mTOR, echo = FALSE}
dataSelPI3K <- dataSezWP[(grep("PI3K", dataSezWP$name,ignore.case=TRUE)),]
dataSelAKT <- dataSezWP[(grep("AKT", dataSezWP$name,ignore.case=TRUE)),]
dataSelmTOR <- dataSezWP[(grep("mTOR", dataSezWP$name,ignore.case=TRUE)),] 
dataSel_PI3KAKTmTOR <- dataSezWP[(grep("PI3K-Akt-mTOR", dataSezWP$name,ignore.case=TRUE)),] 
#dataSel <- dataSezWP[(grep("AKT", dataSezWP$name,ignore.case=TRUE))|(grep("PI3K", dataSezWP$name,ignore.case=TRUE))|(grep("mTOR", dataSezWP$name,ignore.case=TRUE)),] 
dataSel<-dataSel_PI3KAKTmTOR#rbind(dataSelPI3K,dataSelAKT,dataSelmTOR)
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
#dataSel<-as.matrix(dataSel[,-13])
summary(dataSel)
#selThr<-0.6
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="PI3K-Akt-mTOR",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelPI3KAKTmTOR.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="PI3K-Akt-mTOR",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
rownames(dataSel)<-paste0(rownames(dataSel),"_PI3K-Akt-mTOR")
dataSel_PI3KAKTmTOR<-dataSel
summary(dataSel_PI3KAKTmTOR)
write.csv(cbind(rownames(dataSel_PI3KAKTmTOR),dataSel_PI3KAKTmTOR),paste0(inpF,"dataSel_PI3KAKTmTOR2sig.csv"),row.names = F)
```

```{r Apoptosis, echo = FALSE}
dataSel <- dataSezWP[grep("apoptosis", dataSezWP$name,ignore.case=TRUE),]
pathwayN<-sapply(strsplit(row.names(dataSel),";"), `[`, 2)
dataSel<-cbind.data.frame(dataSel,pathwayN)
dataSel=subset(dataSel, !duplicated(pathwayN))
#selThr<-0.3
#limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red")
summary(dataSel[,c(3,4,5,8)])
hist(as.matrix(dataSel[,c(3,4,5,8)]))
#colnames(dataSel)<-sub("_W","W",colnames(dataSel))
limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red")
ggplot2::ggsave(file=paste0(inpD,"vennPlot.dataSelApoptisis.svg"),plot=limma::vennDiagram(dataSel[,c(3,4,5,8)]<selThr,main="Apoptosis",counts.col = "red"))#,  
dataSel<-dataSel[,grep("_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("D_x.y_",colnames(dataSel))]
dataSel<-dataSel[,-grep("C_x.y_",colnames(dataSel))]
#limma::vennDiagram(dataSel[,c(8,3,4,5)]<selThr,main="Apoptosis",counts.col = "red")
#data_apop <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_jak <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_mapk <- data[grep("apoptosis", data$C..Gene.ontology..GO.),] 
#data_jaks <- data[grep("jak", data$C..KEGG.name),] 
#data_mapk <- data[grep("mapk signaling pathway", data$C..KEGG.name),]
#data_selr <- data[grep("MAPK signaling pathway", data$C..KEGG.name),]
#data_selr<-rbind.data.frame(data_apop,data_apop,data_mapk)
rownames(dataSel)<-paste0(rownames(dataSel),"_Apopto")
dataSelApoptosis<-dataSel
summary(dataSelApoptosis)
write.csv(cbind(rownames(dataSelApoptosis),dataSelApoptosis),paste0(inpF,"Apoptosis2sig.csv"),row.names = F)
```

```{r apohc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelApoptosis
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.Apoptosis2sig.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"ApoptosisHC2sig.csv"),row.names = F)
```

```{r mapkhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelMAPK
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.MAPK2sig.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"MAPKhc2sig.csv"),row.names = F)
```

```{r ampkhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelAMPK
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.AMPK2sig.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"AMPKhc2sig.csv"),row.names = F)
```

```{r stathc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSelSTAT
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";","",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=TRUE,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.STAT2sig.svg"),plot=svgPHC)#,
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"STAThc2sig.csv"),row.names = F)
```

```{r pi3kallhc-sel-data-cols, echo = FALSE}
data_selr_s<-dataSel_PI3KAKTmTOR
#library(scales)
data_selr=scales::squish(as.matrix(data_selr_s),c(-3,3))
data_selr[is.na(data_selr)]=0
summary(data_selr)
hist(as.matrix(data_selr))
pathwayN<-sapply(strsplit(row.names(data_selr),"_"), `[`, 1)
data_selr<-cbind.data.frame(data_selr,pathwayN)
data_selr=subset(data_selr, !duplicated(pathwayN))
data_selr<-as.matrix(data_selr[,-13])
summary(data_selr)
#library(pheatmap::pheatmap)
data_selr=data_selr[,c(10,11,12,4,5,6,7,8,9,1,2,3)]
summary(data_selr)
hist(data_selr)
rn<-sub(";"," ",rownames(data_selr))
row.names(data_selr)<-paste(sapply(rn, "[", 1))#,sapply(rn, "[", 3),sapply(rn, "[", 6))
cn<-strsplit(colnames(data_selr), "_")
colnames(data_selr)<-paste(sapply(cn, "[", 1))
bk1 <- c(seq(-3,-0.01,by=0.01))
bk2 <- c(seq(0.01,3,by=0.01))
bk <- c(bk1,bk2)  #combine the break limits for purpose of graphing
my_palette <- c(colorRampPalette(colors = c("darkblue", "white"))(n = length(bk1)-1),
              "gray", "gray",
              c(colorRampPalette(colors = c("white","darkred"))(n = length(bk2)-1)))
svgPHC<-pheatmap::pheatmap(data_selr,clustering_distance_rows = "binary",clustering_distance_cols = "correlation",fontsize_row=6,cluster_cols=FALSE,cluster_rows=T,color = my_palette,fontsize = 6)#,labels_row =  pathwayN,scale="row",annotation_col = label,show_rownames=F)
#library(ggplot2)
ggplot2::ggsave(file=paste0(inpD,"clusterPlot.PI3Ketc2sig.svg"),plot=svgPHC)#,  
write.csv(cbind(rownames(data_selr),data_selr),paste0(inpF,"PI3KetcHC2sig.csv"),row.names = F)
```

```{r DEqMS-peptides}
fit3$count = rowMins(as.matrix(df.prot[,grepl("^Peptides\\.[0-9]+", names(df.prot))]))+1
min(fit3$count)

fit4 = spectraCounteBayes(fit3)
VarianceBoxplot(fit4, n=20, main = hdr,xlab="peptide count + 1")
DEqMS.results = outputResult(fit4,coef_col = 1)
DEqMS.results$Gene.name = df.prot[DEqMS.results$gene,]$Gene.names
head(DEqMS.results)
write.table(DEqMS.results,paste0(inpD,hdr,"R-W.DEqMS.pep.results.txt"),sep = "\t",row.names = F,quote=F)
head(DEqMS.results)
VarianceBoxplot(fit4,n=20)
#peptideProfilePlot(dat=df.prot)#,col=2,gene="TGFBR2")
VarianceScatterplot(fit4, xlab="log2(LFQ)")
limma.prior = fit4$s2.prior
abline(h = log(limma.prior),col="green",lwd=3 )
legend("topright",legend=c("DEqMS prior variance","Limma prior variance"),
        col=c("red","green"),lwd=3)
op <- par(mfrow=c(1,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
Residualplot(fit4,  xlab="log2(PSM count)",main="DEqMS")
x = fit3$count
y = log(limma.prior) - log(fit3$sigma^2)
plot(log2(x),y,ylim=c(-6,2),ylab="Variance(estimated-observed)", pch=20, cex=0.5,
     xlab = "log2(PSMcount)",main="Limma")
#install.packages("LSD")
library(LSD)
op <- par(mfrow=c(1,2), mar=c(4,4,4,1), oma=c(0.5,0.5,0.5,0))
x = fit3$count
y = fit3$s2.post
heatscatter(log2(x),log(y),pch=20, xlab = "log2(PSMcount)", 
     ylab="log(Variance)",
     main="Posterior Variance in Limma")

y = fit4$sca.postvar
heatscatter(log2(x),log(y),pch=20, xlab = "log2(PSMcount)",
     ylab="log(Variance)", 
     main="Posterior Variance in DEqMS")

```


