```{r setup, include=FALSE}
#plot
par(mfrow=c(1,2))
#library/packages
.libPaths( c( .libPaths(), "C:/Users/animeshs/GD/R-4.0.1/library") )
.libPaths()
#[1] "C:/Users/animeshs/GD/R-4.0.1/library"
#install.packages("lattice", repos="http://cran.r-project.org", lib="~/local/R_libs/")
#.libPaths( c( .libPaths(), "C:/Users/animeshs/GD/R_libs") )
#install.packages("writexl")
#install.packages("readxl")
#install.packages("BiocManager")
#BiocManager::install("limma")
#install.packages("matrixStats")
#directory/home
setwd("C:/Users/animeshs/GD/scripts")
getwd()
chkrVector<-c(22.39459,20.48316,21.87155,NA,20.34495)
chkrDF<-as.data.frame(chkrVector)
plot(chkrDF)
hist(as.matrix(chkrDF))
chkrDF[,1]
apply(chkrDF, 2, function(x) t.test(as.numeric(x[c(1:3)]),as.numeric(x[4:5]),na.rm=T,var.equal=T)$p.value)
t.test(as.numeric(chkrVector[c(1:3)]),as.numeric(chkrVector[4:5]),na.rm=T,var.equal=T)$p.value
t.test(as.numeric(c(22.39459,20.48316,21.87155)),as.numeric(c(NA,20.34495)),na.rm=T,var.equal=T)$p.value
t.test(c(22.39459,20.48316,21.87155),c(NA,20.34495),na.rm=T,var.equal=T)$p.value
t.test(c(22.39459,20.48316,21.87155),c(NA,17.97),na.rm=T,var.equal=T)$p.value
t.test(c(21.4316,21.77155),c(NA,17.7),na.rm=T,var.equal=T)$p.value
t.test(c(21.4316,21.77155),c(17.6,17.7),na.rm=T,var.equal=F)$p.value
```

```{r data, echo=FALSE}
#inpD<-"L:\\promec\\USERS\\Synnøve\\20200911_6samples\\HF\\combined\\txt-rabitcrap\\"
inpD <-paste0(getwd(),"/txt_rabitcrap/")
inpF<-paste0(inpD,"proteinGroups.txt")
data <- read.table(inpF,stringsAsFactors = FALSE, header = TRUE, quote = "", comment.char = "", sep = "\t")
#read.delim(inpF,sep="\t",header = T,row.names = 1)
#clean
#data = data[!data$Reverse=="+",]
#data = data[!data$Potential.contaminant=="+",]
#data = data[!data$Only.identified.by.site=="+",]
row.names(data)<-paste(row.names(data),data$Gene.names,data$Protein.IDs,data$Protein.names,data$Score,data$Peptide.counts..unique.,sep=";;")
summary(data)
dim(data)
hist(as.matrix(log2(data[,grep("Intensity",colnames(data))])))
summary(log2(data[,grep("Intensity",colnames(data))]))
selection<-"LFQ.intensity"
LFQ<-as.matrix(data[,grep(selection,colnames(data))])
protNum<-1:ncol(LFQ)
colnames(LFQ)=paste(protNum,sub(selection,"",colnames(LFQ)),protNum,sep="_")
dim(LFQ)
log2LFQ<-log2(LFQ)
log2LFQ[log2LFQ==-Inf]=NA
log2LFQ[log2LFQ==0]=NA
summary(log2LFQ)
hist(log2LFQ)
write.csv(as.data.frame(cbind(log2LFQ,rownames(data))),row.names=F,paste0(inpD,"log2LFQ.csv"))
```

```{r label}
#inpL<-paste0(inpD,"Groups.txt")
#factor(label$annotation)
#inpL<-paste0(inpD,"Groups.xlsx")
#label<-read_xlsx(inpL)
#colnames(label)=sub("\\-[0-9]+","",colnames(label))
#colnames(label)
#table(label)
label<-colnames(log2LFQ)
label
```

```{r Control_2}
Control_2<-as.matrix(log2LFQ[,grep("Control_2",colnames(log2LFQ))])
Control_2[is.na(Control_2)]<-0
hist(as.matrix(Control_2))
limma::vennDiagram(Control_2>0)
```

```{r Control_3}
Control_3<-as.matrix(log2LFQ[,grep("Control_3",colnames(log2LFQ))])
Control_3[is.na(Control_3)]<-0
hist(as.matrix(Control_3))
limma::vennDiagram(Control_3>0)
```

```{r XL_Control_4}
XL_Control_4<-as.matrix(log2LFQ[,grep("XL_Control_4",colnames(log2LFQ))])
XL_Control_4[is.na(XL_Control_4)]<-0
hist(as.matrix(XL_Control_4))
limma::vennDiagram(XL_Control_4>0)
```

```{r APIM_2}
APIM_2<-as.matrix(log2LFQ[,grep("APIM_2",colnames(log2LFQ))])
APIM_2[is.na(APIM_2)]<-0
hist(as.matrix(APIM_2))
limma::vennDiagram(APIM_2>0)
```

```{r APIM_3}
APIM_3<-as.matrix(log2LFQ[,grep("APIM_3",colnames(log2LFQ))])
APIM_3[is.na(APIM_3)]<-0
hist(as.matrix(APIM_3))
limma::vennDiagram(APIM_3>0)
```

```{r XL_APIM_4}
XL_APIM_4<-as.matrix(log2LFQ[,grep("XL_APIM_4",colnames(log2LFQ))])
XL_APIM_4[is.na(XL_APIM_4)]<-0
hist(as.matrix(XL_APIM_4))
limma::vennDiagram(XL_APIM_4>0)
```

```{r medianDiffWSRT}
Control_2[Control_2==0]<-NA
Control_2hda<-apply(Control_2,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
Control_2hda[is.na(Control_2hda)]<-0
summary(Control_2hda)
Control_3[Control_3==0]<-NA
Control_3hda<-apply(Control_3,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
Control_3hda[is.na(Control_3hda)]<-0
summary(Control_3hda)
XL_Control_4[XL_Control_4==0]<-NA
XL_Control_4hda<-apply(XL_Control_4,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
XL_Control_4hda[is.na(XL_Control_4hda)]<-0
summary(XL_Control_4hda)
APIM_2[APIM_2==0]<-NA
APIM_2hda<-apply(APIM_2,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
APIM_2hda[is.na(APIM_2hda)]<-0
summary(APIM_2hda)
APIM_3[APIM_3==0]<-NA
APIM_3hda<-apply(APIM_3,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
APIM_3hda[is.na(APIM_3hda)]<-0
summary(APIM_3hda)
XL_APIM_4[XL_APIM_4==0]<-NA
XL_APIM_4hda<-apply(XL_APIM_4,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
XL_APIM_4hda[is.na(XL_APIM_4hda)]<-0
summary(XL_APIM_4hda)
A2C_2<-APIM_2hda-Control_2hda
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
hist(XL_A2C_4)
hdaM=cbind(A2C_2,A2C_3,XL_A2C_4)
hist(hdaM)
limma::vennDiagram(hdaM>0)
limma::vennDiagram(hdaM<0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{median(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,Control_2,Control_3,XL_Control_4,APIM_2,APIM_3,XL_APIM_4,data[,8])),row.names=F,paste0(inpF,"median-LFQ-APIM-control.csv"))
```

```{r data, echo=FALSE}
#inpD<-"L:\\promec\\USERS\\Synnøve\\20200911_6samples\\HF\\combined\\txt-rabitcrap\\"
inpD <-paste0(getwd(),"/txt_rabitcrap/")
inpF<-paste0(inpD,"proteinGroups.txt")
data <- read.table(inpF,stringsAsFactors = FALSE, header = TRUE, quote = "", comment.char = "", sep = "\t")
#read.delim(inpF,sep="\t",header = T,row.names = 1)
#clean
#data = data[!data$Reverse=="+",]
#data = data[!data$Potential.contaminant=="+",]
#data = data[!data$Only.identified.by.site=="+",]
row.names(data)<-paste(row.names(data),data$Gene.names,data$Protein.IDs,data$Protein.names,data$Score,data$Peptide.counts..unique.,sep=";;")
summary(data)
dim(data)
hist(as.matrix(log2(data[,grep("Intensity",colnames(data))])))
summary(log2(data[,grep("Intensity",colnames(data))]))
selection<-"LFQ.intensity"
LFQ<-as.matrix(data[,grep(selection,colnames(data))])
protNum<-1:ncol(LFQ)
colnames(LFQ)=paste(protNum,sub(selection,"",colnames(LFQ)),protNum,sep="_")
dim(LFQ)
log2LFQ<-log2(LFQ)
log2LFQ[log2LFQ==-Inf]=NA
log2LFQ[log2LFQ==0]=NA
summary(log2LFQ)
hist(log2LFQ)
write.csv(as.data.frame(cbind(log2LFQ,rownames(data))),row.names=F,paste0(inpD,"log2LFQ.csv"))
```

```{r label}
#inpL<-paste0(inpD,"Groups.txt")
#factor(label$annotation)
#inpL<-paste0(inpD,"Groups.xlsx")
#label<-read_xlsx(inpL)
#colnames(label)=sub("\\-[0-9]+","",colnames(label))
#colnames(label)
#table(label)
label<-colnames(log2LFQ)
label
```

```{r Control_2}
Control_2<-as.matrix(log2LFQ[,grep("Control_2",colnames(log2LFQ))])
Control_2[is.na(Control_2)]<-0
hist(as.matrix(Control_2))
limma::vennDiagram(Control_2>0)
```

```{r Control_3}
Control_3<-as.matrix(log2LFQ[,grep("Control_3",colnames(log2LFQ))])
Control_3[is.na(Control_3)]<-0
hist(as.matrix(Control_3))
limma::vennDiagram(Control_3>0)
```

```{r XL_Control_4}
XL_Control_4<-as.matrix(log2LFQ[,grep("XL_Control_4",colnames(log2LFQ))])
XL_Control_4[is.na(XL_Control_4)]<-0
hist(as.matrix(XL_Control_4))
limma::vennDiagram(XL_Control_4>0)
```

```{r APIM_2}
APIM_2<-as.matrix(log2LFQ[,grep("APIM_2",colnames(log2LFQ))])
APIM_2[is.na(APIM_2)]<-0
hist(as.matrix(APIM_2))
limma::vennDiagram(APIM_2>0)
```

```{r APIM_3}
APIM_3<-as.matrix(log2LFQ[,grep("APIM_3",colnames(log2LFQ))])
APIM_3[is.na(APIM_3)]<-0
hist(as.matrix(APIM_3))
limma::vennDiagram(APIM_3>0)
```

```{r XL_APIM_4}
XL_APIM_4<-as.matrix(log2LFQ[,grep("XL_APIM_4",colnames(log2LFQ))])
XL_APIM_4[is.na(XL_APIM_4)]<-0
hist(as.matrix(XL_APIM_4))
limma::vennDiagram(XL_APIM_4>0)
```

```{r medianDiffWSRT}
Control_2[Control_2==0]<-NA
Control_2hda<-apply(Control_2,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
Control_2hda[is.na(Control_2hda)]<-0
summary(Control_2hda)
Control_3[Control_3==0]<-NA
Control_3hda<-apply(Control_3,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
Control_3hda[is.na(Control_3hda)]<-0
summary(Control_3hda)
XL_Control_4[XL_Control_4==0]<-NA
XL_Control_4hda<-apply(XL_Control_4,1,function(x) if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
XL_Control_4hda[is.na(XL_Control_4hda)]<-0
summary(XL_Control_4hda)
APIM_2[APIM_2==0]<-NA
APIM_2hda<-apply(APIM_2,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
APIM_2hda[is.na(APIM_2hda)]<-0
summary(APIM_2hda)
APIM_3[APIM_3==0]<-NA
APIM_3hda<-apply(APIM_3,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
APIM_3hda[is.na(APIM_3hda)]<-0
summary(APIM_3hda)
XL_APIM_4[XL_APIM_4==0]<-NA
XL_APIM_4hda<-apply(XL_APIM_4,1,function(x)  if(sum(!is.na(x))<1){NA}  else{median(x,na.rm=T)})
XL_APIM_4hda[is.na(XL_APIM_4hda)]<-0
summary(XL_APIM_4hda)
A2C_2<-APIM_2hda-Control_2hda
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
hist(XL_A2C_4)
hdaM=cbind(A2C_2,A2C_3,XL_A2C_4)
hist(hdaM)
limma::vennDiagram(hdaM>0)
limma::vennDiagram(hdaM<0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{median(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,Control_2,Control_3,XL_Control_4,APIM_2,APIM_3,XL_APIM_4,data[,8])),row.names=F,paste0(inpF,"median-LFQ-APIM-control.csv"))
```

```{r maxDiffWSRT}
#Control_2[Control_2==1]<-0
Control_2hda<-apply(Control_2,1,function(x) max(x,na.rm=T))
sum(Control_2hda>0)
#Control_3[Control_3==1]<-NA
Control_3hda<-apply(Control_3,1,function(x) max(x,na.rm=T))
sum(Control_3hda>0)
#XL_Control_4[XL_Control_4==1]<-NA
XL_Control_4hda<-apply(XL_Control_4,1,function(x) max(x,na.rm=T))
sum(XL_Control_4hda>0)
#XL_Control_4[XL_Control_4==1]<-NA
APIM_2hda<-apply(APIM_2,1,function(x) max(x,na.rm=T))
sum(APIM_2hda>0)
#XL_Control_4[XL_Control_4==1]<-NA
APIM_3hda<-apply(APIM_3,1,function(x) max(x,na.rm=T))
sum(APIM_3hda>0)
#XL_Control_4[XL_Control_4==1]<-NA
XL_APIM_4hda<-apply(XL_APIM_4,1,function(x) max(x,na.rm=T))
sum(XL_APIM_4hda>0)
A2C_2<-APIM_2hda-Control_2hda
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
hist(XL_A2C_4)
hdaM=cbind(A2C_2,A2C_3,XL_A2C_4)
hist(hdaM)
limma::vennDiagram(hdaM>0)
limma::vennDiagram(hdaM<0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{max(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,data[,8])),row.names=F,paste0(inpF,"max-LFQ-APIM-control.csv"))
```

```{r diffMaxWSRT}
#Control_2[Control_2==1]<-0
Control_2hda<-Control_2
sum(Control_2hda>0)
Control_3hda<-Control_3
sum(Control_3hda>0)
XL_Control_4hda<-XL_Control_4
sum(XL_Control_4hda>0)
APIM_2hda<-APIM_2
sum(APIM_2hda>0)
APIM_3hda<-APIM_3
sum(APIM_3hda>0)
XL_APIM_4hda<-XL_APIM_4
sum(XL_APIM_4hda>0)
A2C_2<-APIM_2hda-Control_2hda
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
hist(XL_A2C_4)
A2C_2hda<-apply(A2C_2,1,function(x) max(x,na.rm=T))
sum(A2C_2hda>0)
A2C_3hda<-apply(A2C_3,1,function(x) max(x,na.rm=T))
sum(A2C_3hda>0)
XL_A2C_4hda<-apply(XL_A2C_4,1,function(x) max(x,na.rm=T))
sum(XL_A2C_4hda>0)
hdaM=cbind(A2C_2hda,A2C_3hda,XL_A2C_4hda)
hist(hdaM)
limma::vennDiagram(hdaM<0)
limma::vennDiagram(hdaM>0)
#limma::vennDiagram(hdaM==0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{max(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,data[,8])),row.names=F,paste0(inpF,"maxDiff-LFQ-APIM-control.csv"))
```

```{r diffMedianWSRT}
#Control_2[Control_2==1]<-0
Control_2hda<-Control_2
sum(Control_2hda>0)
Control_3hda<-Control_3
sum(Control_3hda>0)
XL_Control_4hda<-XL_Control_4
sum(XL_Control_4hda>0)
APIM_2hda<-APIM_2
sum(APIM_2hda>0)
APIM_3hda<-APIM_3
sum(APIM_3hda>0)
XL_APIM_4hda<-XL_APIM_4
sum(XL_APIM_4hda>0)
A2C_2<-APIM_2hda-Control_2hda
A2C_2[A2C_2==0]<-NA
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
A2C_3[A2C_3==0]<-NA
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
XL_A2C_4[XL_A2C_4==0]<-NA
hist(XL_A2C_4)
A2C_2hda<-apply(A2C_2,1,function(x) median(x,na.rm=T))
summary(A2C_2hda)
A2C_3hda<-apply(A2C_3,1,function(x) median(x,na.rm=T))
summary(A2C_3hda)
XL_A2C_4hda<-apply(XL_A2C_4,1,function(x) median(x,na.rm=T))
summary(XL_A2C_4hda)
hdaM=cbind(A2C_2hda,A2C_3hda,XL_A2C_4hda)
hist(hdaM)
limma::vennDiagram(hdaM<0)
limma::vennDiagram(hdaM>0)
#limma::vennDiagram(hdaM==0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{median(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,data[,8])),row.names=F,paste0(inpF,"medianDiff-LFQ-APIM-control.csv"))
```

```{r diffMinWSRT}
#Control_2[Control_2==1]<-0
Control_2hda<-Control_2
sum(Control_2hda>0)
Control_3hda<-Control_3
sum(Control_3hda>0)
XL_Control_4hda<-XL_Control_4
sum(XL_Control_4hda>0)
APIM_2hda<-APIM_2
sum(APIM_2hda>0)
APIM_3hda<-APIM_3
sum(APIM_3hda>0)
XL_APIM_4hda<-XL_APIM_4
sum(XL_APIM_4hda>0)
A2C_2<-APIM_2hda-Control_2hda
A2C_2[A2C_2==0]<-NA
hist(A2C_2)
A2C_3<-APIM_3hda-Control_3hda
A2C_3[A2C_3==0]<-NA
hist(A2C_3)
XL_A2C_4<-XL_APIM_4hda-XL_Control_4hda
XL_A2C_4[XL_A2C_4==0]<-NA
hist(XL_A2C_4)
A2C_2hda<-apply(A2C_2,1,function(x) if(sum(!is.na(x))<2){NA}  else{min(x,na.rm=T)})
summary(A2C_2hda)
A2C_3hda<-apply(A2C_3,1,function(x)  if(sum(!is.na(x))<2){NA}  else{min(x,na.rm=T)})
summary(A2C_3hda)
XL_A2C_4hda<-apply(XL_A2C_4,1,function(x)  if(sum(!is.na(x))<2){NA}  else{min(x,na.rm=T)})
summary(XL_A2C_4hda)
hdaM=cbind(A2C_2hda,A2C_3hda,XL_A2C_4hda)
hist(hdaM)
limma::vennDiagram(hdaM<0)
limma::vennDiagram(hdaM>0)
#limma::vennDiagram(hdaM==0)
hdaM[hdaM==0]<-NA
options(nwarnings = 1000000)
pVal0 = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
options(nwarnings = 1000000)
hdaMax = apply(
  hdaM, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{min(as.numeric(x),na.rm=T)}
  )
summary(warnings())
#hist(hdaMax)
Uniprot<-sapply(strsplit(data[,1],";"), `[`, 1)
uniprot<-sapply(strsplit(Uniprot,"-",fixed=TRUE),`[`,1)
row.names(hdaM)<-uniprot
#colnames(hdaM)<-paste(sapply(cn, "[", 2),sapply(cn, "[", 4))
gene<-toupper(as.character(data$Gene.names))
gen<-as.character(sapply(strsplit(gene,";"), `[`, 1))
protein<-as.character(data$Protein.IDs)
summary(hdaM)
#limma::vennDiagram(hdaM[,1:5]>0)
write.csv(as.data.frame(cbind(uniprot,gen,WSRT=pVal0,Log2Cmax=hdaMax,hdaM,data[,8])),row.names=F,paste0(inpF,"minDiff-LFQ-APIM-control.csv"))
```

```{r S_WSRT, echo = FALSE}
ctr<-as.matrix(log2LFQ[,grep("_1_",colnames(log2LFQ))])
ctr[is.na(ctr)]<-0
hist(ctr)
S<-as.matrix(log2LFQ[,grep("_2_",colnames(log2LFQ))])
S[is.na(S)]<-0
hist(S)
dataSellog2grpWSRT<-(S-ctr)
hist(dataSellog2grpWSRT)
#dataSellog2grpWSRT<-dataSellog2grpWSRT[,-ncol(dataSellog2grpWSRT)]
summary(dataSellog2grpWSRT)
dataSellog2grpWSRT[dataSellog2grpWSRT==0]<-NA
hist(dataSellog2grpWSRT)
summary(dataSellog2grpWSRT)
min(dataSellog2grpWSRT,na.rm=T)
max(dataSellog2grpWSRT,na.rm=T)
dim(dataSellog2grpWSRT)
options(nwarnings = 1000000)
minNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{min(x,na.rm=T)}
  )
summary(warnings())
hist(minNA)
maxNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{max(x,na.rm=T)}
  )
summary(warnings())
hist(maxNA)
hist(maxNA-minNA)
pValNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
hist(pValNA)
S_dataSellog2grpWSRT<-cbind(uniprot,dataSellog2grpWSRT,pValNA,data[,7],rownames(dataSellog2grpWSRT))
#writexl::write_xlsx(as.data.frame(S_dataSellog2grpWSRT),paste0(inpF,"sel-LFQ-S-control.WSRT.xlsx"))
write.csv(as.data.frame(S_dataSellog2grpWSRT),row.names=F,paste0(inpF,"sel-LFQ-S-control.WSRT.csv"))
```

```{r S_wsrtMatlab, echo = FALSE}
inpM<-"L:\\promec\\HF\\Lars\\2020\\AUGUST\\siri\\combined\\txt_PHOSTY\\proteinGroups.txt WSRTpVal.csv"
hdr<-read.csv(inpM,skip=1,header=F,nrows=1,as.is=T)
resMatlab<-read.csv(inpM, skip = 2, header = F)
colnames(resMatlab)<-hdr
summary(resMatlab)
hist(as.matrix(resMatlab[,5]))#-dataSellog2grpWSRT[,1]))#,(resMatlab[,7]+dataSellog2grpWSRT[,1]))
hist(pValNA)
hist(as.matrix(resMatlab[,6])-pValNA)
plot(as.matrix(resMatlab[,6]),pValNA)
```


```{r MDR_WSRT, echo = FALSE}
ctr<-as.matrix(log2LFQ[,grep("_1_",colnames(log2LFQ))])
ctr[is.na(ctr)]<-0
hist(ctr)
M<-as.matrix(log2LFQ[,grep("_3_",colnames(log2LFQ))])
M[is.na(M)]<-0
hist(M)
dataSellog2grpWSRT<-(M-ctr)
hist(dataSellog2grpWSRT)
#dataSellog2grpWSRT<-dataSellog2grpWSRT[,-ncol(dataSellog2grpWSRT)]
summary(dataSellog2grpWSRT)
dataSellog2grpWSRT[dataSellog2grpWSRT==0]<-NA
hist(dataSellog2grpWSRT)
summary(dataSellog2grpWSRT)
min(dataSellog2grpWSRT,na.rm=T)
max(dataSellog2grpWSRT,na.rm=T)
dim(dataSellog2grpWSRT)
options(nwarnings = 1000000)
minNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{min(x,na.rm=T)}
  )
summary(warnings())
hist(minNA)
maxNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{max(x,na.rm=T)}
  )
summary(warnings())
hist(maxNA)
hist(maxNA-minNA)
pValNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
hist(pValNA)
inpW<-paste0(inpF,"sel-LFQ-MDR-control.WSRT.xlsx")
MDR_dataSellog2grpWSRT<-cbind(uniprot,dataSellog2grpWSRT,pValNA,data[,7],rownames(dataSellog2grpWSRT))
#writexl::write_xlsx(as.data.frame(MDR_dataSellog2grpWSRT),inpW)
write.csv(as.data.frame(MDR_dataSellog2grpWSRT),row.names=F,paste0(inpF,"sel-LFQ-MDR-control.WSRT.csv"))
```

```{r comb_WSRT, echo = FALSE}
ctr<-as.matrix(log2LFQ[,grep("_1_",colnames(log2LFQ))])
ctr[is.na(ctr)]<-0
hist(ctr)
C<-as.matrix(log2LFQ[,grep("_4_",colnames(log2LFQ))])
C[is.na(C)]<-0
hist(C)
dataSellog2grpWSRT<-(C-ctr)
hist(dataSellog2grpWSRT)
#dataSellog2grpWSRT<-dataSellog2grpWSRT[,-ncol(dataSellog2grpWSRT)]
summary(dataSellog2grpWSRT)
dataSellog2grpWSRT[dataSellog2grpWSRT==0]<-NA
hist(dataSellog2grpWSRT)
summary(dataSellog2grpWSRT)
min(dataSellog2grpWSRT,na.rm=T)
max(dataSellog2grpWSRT,na.rm=T)
dim(dataSellog2grpWSRT)
options(nwarnings = 1000000)
minNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{min(x,na.rm=T)}
  )
summary(warnings())
hist(minNA)
maxNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else{max(x,na.rm=T)}
  )
summary(warnings())
hist(maxNA)
hist(maxNA-minNA)
pValNA = apply(
  dataSellog2grpWSRT, 1, function(x)
    if(sum(!is.na(x))<2){NA}
    else if(mode(x)==median(x,na.rm=T)){0}
    else{wilcox.test(as.numeric(x),na.rm=T)$p.value}
  )
summary(warnings())
hist(pValNA)
inpW<-paste0(inpF,"sel-LFQ-combi-control.WSRT.xlsx")
combi_dataSellog2grpWSRT<-cbind(uniprot,dataSellog2grpWSRT,pValNA,data[,7],rownames(dataSellog2grpWSRT))
#writexl::write_xlsx(as.data.frame(combi_dataSellog2grpWSRT),inpW)
write.csv(as.data.frame(combi_dataSellog2grpWSRT),row.names=F,paste0(inpF,"sel-LFQ-combi-control.WSRT.csv"))
```

```{r sel-WSRTs}
selThr<-0.3
dataS<-cbind(S_dataSellog2grpWSRT,MDR_dataSellog2grpWSRT,combi_dataSellog2grpWSRT)
dataScom<-dataS[(dataS[,5]<selThr) & (dataS[,12]<selThr) & (dataS[,19]<selThr),]
dataSel<-dataS[,c(5,12,19)]
dataSel[dataSel==0]<-1
dataSel[is.na(dataSel)]<-1
colnames(dataSel)<-c("S","MDR","comb")
hist(as.numeric(dataSel))
limma::vennDiagram(dataSel[,c(1:3)]<selThr)
gene<-sapply(strsplit(row.names(dataSel),";;"), `[`, 2)
#gene<-sapply(strsplit(gene,";"), `[`, 1)
dataSel<-cbind(gene,dataSel)#[,ncol(dataSel)+1]<-
writexl::write_xlsx(as.data.frame(dataS),paste0(inpF,"sel-WSRT-onevar.xlsx"))
write.csv(as.data.frame(dataS),row.names=FALSE,paste0(inpF,"sel-WSRT-onevar.csv"))
```

```{r SOS-map}
#https://www.asmscience.org/content/journal/ecosalplus/10.1128/ecosalplus.5.4.3
##Table1
sosD<-read.csv(paste0(inpD,"sosList.txt"),header=T,sep="\t")
#gene<-sapply(strsplit(sosD[,1],";"), `[`, 1)
sosD<-unique(data.frame(gene=unlist(strsplit(as.character(sosD$LexA.dependent.genes),";"))))
#sosD<-cbind(gene,sosD)
#table1<-merge(x=sosD,y=dataSel,by="gene",all=TRUE)
rownames(sosD)<-toupper(sosD$gene)
sosD$gene<-0.25
colnames(sosD)<-c("sosD")
sosD
```

```{r SOSlike-map}
#https://www.asmscience.org/content/journal/ecosalplus/10.1128/ecosalplus.5.4.3
##Table2
sosLD<-read.csv(paste0(inpD,"sosLikeList.txt"),header=T,sep="\t")
#gene<-sapply(strsplit(sosLD[,1],";"), `[`, 1)
sosLD<-unique(data.frame(gene=unlist(strsplit(as.character(sosLD$Genes.with.potential.SOS.boxes.a),";"))))
#sosLD<-sosLD[-grep("ORF_within",sosLD),]
sosLD<-as.data.frame(sosLD[!sosLD$gene=="ORF_within", ])
rownames(sosLD)<-toupper(sosLD$`sosLD[!sosLD$gene == "ORF_within", ]`)
sosLD$`sosLD[!sosLD$gene == "ORF_within", ]`<-0.25
colnames(sosLD)<-c("sosLD")
sosLD
```

```{r SOSboth}
overlapSOS<-merge(sosD,sosLD,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
hist(as.matrix(overlapSOS))
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"sosBoth.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"sosBoth.csv"))
```

```{r SdataSel-map}
dataSelmapS<-unique(data.frame(gene=unlist(strsplit(dataSel[dataSel[,2]=="0.25",1],";"))))
rownames(dataSelmapS)<-toupper(dataSelmapS$gene)
dataSelmapS$gene<-0.25
colnames(dataSelmapS)<-c("S")
dataSelmapS
```

```{r MDRdataSel-map}
dataSelmapMDR<-unique(data.frame(gene=unlist(strsplit(dataSel[dataSel[,3]=="0.25",1],";"))))
rownames(dataSelmapMDR)<-toupper(dataSelmapMDR$gene)
dataSelmapMDR$gene<-0.25
colnames(dataSelmapMDR)<-c("MDR")
dataSelmapMDR
```

```{r combDataSel-map}
dataSelmapComb<-unique(data.frame(gene=unlist(strsplit(dataSel[dataSel[,4]=="0.25",1],";"))))
rownames(dataSelmapComb)<-toupper(dataSelmapComb$gene)
dataSelmapComb$gene<-0.25
colnames(dataSelmapComb)<-c("comb")
dataSelmapComb
```

```{r overlapSOSboth}
overlapSOS<-sosD
colnames(overlapSOS)<-c("sosLD")
overlapSOS<-rbind(overlapSOS,sosLD)
#overlapSOS<-merge(sosD,sosLD,all=T,by="row.names")
#rownames(overlapSOS)<-overlapSOS$Row.names
#overlapSOS<-overlapSOS[,-1]
#overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapS,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapMDR,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapComb,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
hist(as.matrix(overlapSOS))
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"sosMapBoth.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"sosMapBoth.csv"))
```

```{r HCoverlapSOS, echo = FALSE}
data_selr<-overlapSOS
data_selr<-data_selr[data_selr$sosLD<selThr&(data_selr$S<selThr|data_selr$comb<selThr|data_selr$MDR<selThr),]
#limma::vennDiagram(data_selr<selThr,main="SOS",counts.col = "red")
#install.packages("scales")
data_selr[data_selr==1]=NaN
data_selr=data_selr+rnorm(nrow(data_selr))/ncol(data_selr)
data_selr=scales::squish(as.matrix(data_selr),c(-1,1))
summary(data_selr)
#install.packages("pheatmap")
svgPHC<-pheatmap::pheatmap(data_selr,fontsize_row=6,cluster_rows=T,cluster_cols=T)#TRUE)
#install.packages("svglite")
#install.packages("ggplot2")
ggplot2::ggsave(file=paste0(inpF,"clusterPlot.HCoverlapSOS.svg"),plot=svgPHC)#,  
```

```{r data3con2ctr, echo = FALSE}
data3con2ctr<-data.frame(dataS[,c(2:4,9:11,16:18)], stringsAsFactors=F)
data3con2ctr<-as.data.frame(sapply(data3con2ctr,as.numeric))
#data3con2ctr[data3con2ctr==0]=NaN
#rownames(data3con2ctr)<-toupper(dataS)
data3con2ctr=scales::squish(as.matrix(data3con2ctr),c(-3,3))
#data3con2ctr=data3con2ctr[complete.cases(data3con2ctr),]
summary(data3con2ctr)
c<-1
hist(as.numeric(data3con2ctr[,c(c,c+3,c+6)]))
c<-3
hist(as.numeric(data3con2ctr[,c(c,c+3,c+6)]))
```

```{r data3con2ctr, echo = FALSE}
gene<-sapply(strsplit(rownames(dataS),";;"), `[`,2)
gene<-toupper(sapply(strsplit(gene,";",fixed=TRUE),`[`,1))
geneNum<-1:length(gene)
gene[is.na(gene)]<-geneNum[is.na(gene)]
rownames(data3con2ctr)<-gene
data3con2ctr<-data3con2ctr[grep("ruv", row.names(data3con2ctr),ignore.case=TRUE),]
#svgPHC<-pheatmap::pheatmap(data3con2ctr,fontsize_row=6,cluster_rows=T,cluster_cols=T)#TRUE)
svgPHC<-pheatmap::pheatmap(data3con2ctr,fontsize_row=6,cluster_rows=F,cluster_cols=F)#TRUE)
ggplot2::ggsave(file=paste0(inpF,"clusterPlot.ruvHC.svg"),plot=svgPHC)#,  
```

```{r HCoverlapSOS, echo = FALSE}
data3con2ctrS<-data.frame(dataS[,c(2:4,9:11,16:18)], stringsAsFactors=F)
#gene<-unique(data.frame(gene=unlist(strsplit(rownames(dataS),";;"))))
data3con2ctrS<-as.data.frame(sapply(data3con2ctrS,as.numeric))
data3con2ctrS[data3con2ctrS==0]=NaN
data3con2ctrS=scales::squish(as.matrix(data3con2ctrS),c(-3,3))
gene<-sapply(strsplit(rownames(dataS),";;"), `[`,2)
gene<-toupper(sapply(strsplit(gene,";",fixed=TRUE),`[`,1))
geneNum<-1:length(gene)
gene[is.na(gene)]<-geneNum[is.na(gene)]
rownames(data3con2ctrS)<-gene
data3con2ctrS<-merge(overlapSOS[overlapSOS$sosLD=="0.25"&(overlapSOS$comb=="0.25"|overlapSOS$MDR=="0.25"|overlapSOS$S=="0.25"),],data3con2ctrS,all.x=T,by="row.names")
rownames(data3con2ctrS)<-data3con2ctrS$Row.names
data3con2ctrS<-data3con2ctrS[,-1]
writexl::write_xlsx(as.data.frame(cbind(row.names(data3con2ctrS),data3con2ctrS)),paste0(inpF,"sosMapBothSel19.xlsx"))
write.csv(as.data.frame(cbind(row.names(data3con2ctrS),data3con2ctrS)),row.names=FALSE,paste0(inpF,"sosMapBothSel19.csv"))
summary(as.numeric(data3con2ctrS))
c<-4
hist(as.matrix(data3con2ctrS[,c(c,c+3,c+6)]))
c<-5
hist(as.numeric(data3con2ctrS[,c(c,c+3,c+6)]))
svgPHC<-pheatmap::pheatmap(data3con2ctrS[,c(5:13)],fontsize_row=6,cluster_rows=T,clustering_distance_rows = "binary",cluster_cols=F,)#TRUE)
ggplot2::ggsave(file=paste0(inpF,"clusterPlot.HCoverlapSOScombSel19.svg"),plot=svgPHC)#,  
```

```{r S_aureus_SOS-map}
#https://jb.asm.org/content/189/2/531/figures-only
##Table2
sosSa<-read.csv(paste0(inpD,"sosListSA.txt"),header=T,sep="\t")
sosSa<-unique(data.frame(gene=unlist(strsplit(as.character(sosSa$Gene),";"))))
rownames(sosSa)<-toupper(sosSa$gene)
sosSa$gene<-0.25
colnames(sosSa)<-c("sosSa")
sosSa#GENE and empty lines missing, compare with bash tools below
#~ » awk -F '\t' '{print toupper($2)}' $HOME/GD/scripts/txt_PHOSTY/sosListSA.txt | sort -r | uniq -c | wc
#97     193    1257
```

```{r SAoverlapSOS}
overlapSOS<-sosSa
overlapSOS<-merge(overlapSOS,dataSelmapS,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapMDR,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapComb,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"sosMapSa.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"sosMapSa.csv"))
```

```{r non_SOS-map}
#Marit's PPT
nonSOSdata<-read.csv(paste0(inpD,"nonSOSlist.txt"),header=T,sep="\t")
nonSOS<-as.data.frame(nonSOSdata$GENE)
rownames(nonSOS)<-toupper(nonSOSdata$GENE)
colnames(nonSOS)<-c("nonSOS")
nonSOS$nonSOS<-0.25
nonSOS#GENE and empty lines missing, compare with bash tools below
#~ » awk -F '\t' '{print toupper($2)}' $HOME/GD/scripts/txt_PHOSTY/sosListSA.txt | sort -r | uniq -c | wc
#97     193    1257
```

```{r nonSOSoverlap}
overlapSOS<-nonSOS
overlapSOS<-merge(overlapSOS,dataSelmapS,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapMDR,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapComb,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
hist(as.matrix(overlapSOS))
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"NONsosMapSa.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"NONsosMapSa.csv"))
```

```{r nonSOS_HCoverlap, echo = FALSE}
data3con2ctrNS<-data.frame(dataS[,c(2:4,9:11,16:18)], stringsAsFactors=F)
#gene<-unique(data.frame(gene=unlist(strsplit(rownames(dataS),";;"))))
data3con2ctrNS<-sapply(data3con2ctrNS,as.numeric)
hist(data3con2ctrNS)
data3con2ctrNS[data3con2ctrNS==0]=NaN
data3con2ctrNS=scales::squish(as.matrix(data3con2ctrNS),c(-3,3))
hist(data3con2ctrNS)
gene<-sapply(strsplit(rownames(dataS),";;"), `[`,2)
gene<-toupper(sapply(strsplit(gene,";",fixed=TRUE),`[`,1))
geneNum<-1:length(gene)
gene[is.na(gene)]<-geneNum[is.na(gene)]
rownames(data3con2ctrNS)<-gene
data3con2ctrNS<-merge(overlapSOS[overlapSOS$nonSOS=="0.25"&(overlapSOS$comb=="0.25"|overlapSOS$MDR=="0.25"|overlapSOS$S=="0.25"),],data3con2ctrNS,all.x=T,by="row.names")
rownames(data3con2ctrNS)<-data3con2ctrNS$Row.names
data3con2ctrNS<-data3con2ctrNS[,-1]
writexl::write_xlsx(as.data.frame(cbind(row.names(data3con2ctrNS),data3con2ctrNS)),paste0(inpF,"NONsosMapSel29.xlsx"))
write.csv(as.data.frame(cbind(row.names(data3con2ctrNS),data3con2ctrNS)),row.names=FALSE,paste0(inpF,"NONsosMapSel29.csv"))
summary(data3con2ctrNS)
c<-5
hist(as.matrix(data3con2ctrNS[,c(c,c+3,c+6)]))
c<-6
hist(as.matrix(data3con2ctrNS[,c(c,c+3,c+6)]))
svgPHC<-pheatmap::pheatmap(data3con2ctrNS[,c(5:13)],fontsize_row=6,cluster_cols=F,cluster_rows=F)
ggplot2::ggsave(file=paste0(inpF,"clusterPlot.nonSOS.HCoverlapcombSel29.svg"),plot=svgPHC)
```

```{r overlapSOS}
overlapSOS<-sosD
overlapSOS<-merge(overlapSOS,dataSelmapS,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapMDR,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapComb,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
hist(as.matrix(overlapSOS))
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"sosMap.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"sosMap.csv"))
```

```{r overlapSOSlike}
overlapSOS<-sosLD
overlapSOS<-merge(overlapSOS,dataSelmapS,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapMDR,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS<-merge(overlapSOS,dataSelmapComb,all=T,by="row.names")
rownames(overlapSOS)<-overlapSOS$Row.names
overlapSOS<-overlapSOS[,-1]
overlapSOS[overlapSOS==0]<-1
overlapSOS[is.na(overlapSOS)]<-1
hist(as.matrix(overlapSOS))
limma::vennDiagram(overlapSOS<selThr)
writexl::write_xlsx(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),paste0(inpF,"sosLikeMap.xlsx"))
write.csv(as.data.frame(cbind(row.names(overlapSOS),overlapSOS)),row.names=FALSE,paste0(inpF,"sosLikeMap.csv"))
```

```{r S_tTest, echo = FALSE}
dataSellog2grpTtest<-cbind(S,ctr)
dataSellog2grpTtest[dataSellog2grpTtest==0]<-NA
row.names(dataSellog2grpTtest)<-row.names(data)
sCol<-1
eCol<-6
mCol<-3
t.test(as.numeric(dataSellog2grpTtest[1,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[1,c((mCol+1):eCol)]),na.rm=T)$p.value
chkr<-1
sum(!is.na(dataSellog2grpTtest[chkr,c(1:eCol)]))
t.test(as.numeric(dataSellog2grpTtest[chkr,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[chkr,c((mCol+1):eCol)]),na.rm=T)$p.value
dim(dataSellog2grpTtest)
options(nwarnings = 1000000)
pValNA = apply(
  dataSellog2grpTtest, 1, function(x)
    if(sum(!is.na(x[c(sCol:mCol)]))<2&sum(!is.na(x[c((mCol+1):eCol)]))<2){NA}
    else if(sum(is.na(x[c(sCol:mCol)]))==0&sum(is.na(x[c((mCol+1):eCol)]))==0){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),var.equal=F)$p.value}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>1&sum(!is.na(x[c((mCol+1):eCol)]))<1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))<1&sum(!is.na(x[c((mCol+1):eCol)]))>1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<=max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>=min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<=max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>=min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))>=2){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),na.rm=T,var.equal=F)$p.value}
  else{NA}
  )
summary(warnings())
hist(pValNA)
pValNAdm<-cbind(pValNA,dataSellog2grpTtest,row.names(data))
pValNAminusLog10 = -log10(pValNA+.Machine$double.xmin)
hist(pValNAminusLog10)
library(scales)
pValNAminusLog10=squish(pValNAminusLog10,c(0,5))
hist(pValNAminusLog10)
pValBHna = p.adjust(pValNA,method = "BH")
hist(pValBHna)
pValBHnaMinusLog10 = -log10(pValBHna+.Machine$double.xmin)
hist(pValBHnaMinusLog10)
dataSellog2grpTtestNum<-apply(dataSellog2grpTtest, 2,as.numeric)
logFCmedianGrp1 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c(sCol:mCol)],na.rm=T)
logFCmedianGrp2 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c((mCol+1):eCol)],na.rm=T)
logFCmedianGrp1[is.nan(logFCmedianGrp1)]=0
logFCmedianGrp2[is.nan(logFCmedianGrp2)]=0
logFCmedian = logFCmedianGrp1-logFCmedianGrp2
logFCmedianFC = 2^(logFCmedian+.Machine$double.xmin)
logFCmedianFC=squish(logFCmedianFC,c(0.01,100))
hist(logFCmedianFC)
log2FCmedianFC=log2(logFCmedianFC)
hdr<-gsub("[^[:alnum:] ]", "",inpF)
hist(log2FCmedianFC,main = hdr)
rowName<-paste(sapply(strsplit(paste(sapply(strsplit(rownames(dataSellog2grpTtest), ";"), "[", 1)), "-"), "[", 1))
ttest.results = data.frame(Uniprot=rowName,PValueMinusLog10=pValNAminusLog10,FoldChanglog2median=logFCmedianFC,CorrectedPValueBH=pValBHna,TtestPval=pValNA,dataSellog2grpTtest,Log2MedianChange=logFCmedian,RowGeneUniProtScorePeps=rownames(dataSellog2grpTtest))
writexl::write_xlsx(ttest.results,paste0(inpF,selection,sCol,eCol,hdr,"wTestBHgrpOut25pQ.xlsx"))
#limma::vennDiagram(cbind(as.matrix(dataSellog2grpTtest[,c(sCol:mCol)]),as.matrix(dataSellog2grpTtest[,c((mCol+1):eCol)])))
limma::vennDiagram(cbind(logFCmedianGrp1,logFCmedianGrp2))
```


```{r M_tTest, echo = FALSE}
dataSellog2grpTtest<-cbind(MDR,ctr)
dataSellog2grpTtest[dataSellog2grpTtest==0]<-NA
row.names(dataSellog2grpTtest)<-row.names(data)
sCol<-1
eCol<-6
mCol<-3
t.test(as.numeric(dataSellog2grpTtest[1,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[1,c((mCol+1):eCol)]),na.rm=T)$p.value
chkr<-1
sum(!is.na(dataSellog2grpTtest[chkr,c(1:eCol)]))
t.test(as.numeric(dataSellog2grpTtest[chkr,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[chkr,c((mCol+1):eCol)]),na.rm=T)$p.value
dim(dataSellog2grpTtest)
options(nwarnings = 1000000)
pValNA = apply(
  dataSellog2grpTtest, 1, function(x)
    if(sum(!is.na(x[c(sCol:mCol)]))<2&sum(!is.na(x[c((mCol+1):eCol)]))<2){NA}
    else if(sum(is.na(x[c(sCol:mCol)]))==0&sum(is.na(x[c((mCol+1):eCol)]))==0){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),var.equal=F)$p.value}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>1&sum(!is.na(x[c((mCol+1):eCol)]))<1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))<1&sum(!is.na(x[c((mCol+1):eCol)]))>1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<=max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>=min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<=max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>=min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))>=2){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),na.rm=T,var.equal=F)$p.value}
  else{NA}
  )
summary(warnings())
hist(pValNA)
pValNAdm<-cbind(pValNA,dataSellog2grpTtest,row.names(data))
pValNAminusLog10 = -log10(pValNA+.Machine$double.xmin)
hist(pValNAminusLog10)
library(scales)
pValNAminusLog10=squish(pValNAminusLog10,c(0,5))
hist(pValNAminusLog10)
pValBHna = p.adjust(pValNA,method = "BH")
hist(pValBHna)
pValBHnaMinusLog10 = -log10(pValBHna+.Machine$double.xmin)
hist(pValBHnaMinusLog10)
dataSellog2grpTtestNum<-apply(dataSellog2grpTtest, 2,as.numeric)
logFCmedianGrp1 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c(sCol:mCol)],na.rm=T)
logFCmedianGrp2 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c((mCol+1):eCol)],na.rm=T)
logFCmedianGrp1[is.nan(logFCmedianGrp1)]=0
logFCmedianGrp2[is.nan(logFCmedianGrp2)]=0
logFCmedian = logFCmedianGrp1-logFCmedianGrp2
logFCmedianFC = 2^(logFCmedian+.Machine$double.xmin)
logFCmedianFC=squish(logFCmedianFC,c(0.01,100))
hist(logFCmedianFC)
log2FCmedianFC=log2(logFCmedianFC)
hdr<-gsub("[^[:alnum:] ]", "",inpF)
hist(log2FCmedianFC,main = hdr)
rowName<-paste(sapply(strsplit(paste(sapply(strsplit(rownames(dataSellog2grpTtest), ";"), "[", 1)), "-"), "[", 1))
ttest.results = data.frame(Uniprot=rowName,PValueMinusLog10=pValNAminusLog10,FoldChanglog2median=logFCmedianFC,CorrectedPValueBH=pValBHna,TtestPval=pValNA,dataSellog2grpTtest,Log2MedianChange=logFCmedian,RowGeneUniProtScorePeps=rownames(dataSellog2grpTtest))
writexl::write_xlsx(ttest.results,paste0(inpF,selection,sCol,eCol,hdr,"wTestBHgrpOut25pM.xlsx"))
#limma::vennDiagram(cbind(as.matrix(dataSellog2grpTtest[,c(sCol:mCol)]),as.matrix(dataSellog2grpTtest[,c((mCol+1):eCol)])))
limma::vennDiagram(cbind(logFCmedianGrp1,logFCmedianGrp2))
```


```{r C_tTest, echo = FALSE}
dataSellog2grpTtest<-cbind(comb,ctr)
dataSellog2grpTtest[dataSellog2grpTtest==0]<-NA
row.names(dataSellog2grpTtest)<-row.names(data)
sCol<-1
eCol<-6
mCol<-3
t.test(as.numeric(dataSellog2grpTtest[1,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[1,c((mCol+1):eCol)]),na.rm=T)$p.value
chkr<-1
sum(!is.na(dataSellog2grpTtest[chkr,c(1:eCol)]))
t.test(as.numeric(dataSellog2grpTtest[chkr,c(sCol:mCol)]),as.numeric(dataSellog2grpTtest[chkr,c((mCol+1):eCol)]),na.rm=T)$p.value
dim(dataSellog2grpTtest)
options(nwarnings = 1000000)
pValNA = apply(
  dataSellog2grpTtest, 1, function(x)
    if(sum(!is.na(x[c(sCol:mCol)]))<2&sum(!is.na(x[c((mCol+1):eCol)]))<2){NA}
    else if(sum(is.na(x[c(sCol:mCol)]))==0&sum(is.na(x[c((mCol+1):eCol)]))==0){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),var.equal=F)$p.value}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>1&sum(!is.na(x[c((mCol+1):eCol)]))<1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))<1&sum(!is.na(x[c((mCol+1):eCol)]))>1){0}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))<=max(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))==1&(as.numeric(quantile(as.numeric(x[c(sCol:mCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c(sCol:mCol)]),na.rm=T)))>=min(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[1])-(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))<=max(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))==1&sum(!is.na(x[c((mCol+1):eCol)]))>=2&(as.numeric(quantile(as.numeric(x[c((mCol+1):eCol)]),na.rm=T)[5])+(1.5*IQR(as.numeric(x[c((mCol+1):eCol)]),na.rm=T))>=min(as.numeric(x[c(sCol:mCol)]),na.rm=T))){1}
    else if(sum(!is.na(x[c(sCol:mCol)]))>=2&sum(!is.na(x[c((mCol+1):eCol)]))>=2){
      t.test(as.numeric(x[c(sCol:mCol)]),as.numeric(x[c((mCol+1):eCol)]),na.rm=T,var.equal=F)$p.value}
  else{NA}
  )
summary(warnings())
hist(pValNA)
pValNAdm<-cbind(pValNA,dataSellog2grpTtest,row.names(data))
pValNAminusLog10 = -log10(pValNA+.Machine$double.xmin)
hist(pValNAminusLog10)
library(scales)
pValNAminusLog10=squish(pValNAminusLog10,c(0,5))
hist(pValNAminusLog10)
pValBHna = p.adjust(pValNA,method = "BH")
hist(pValBHna)
pValBHnaMinusLog10 = -log10(pValBHna+.Machine$double.xmin)
hist(pValBHnaMinusLog10)
dataSellog2grpTtestNum<-apply(dataSellog2grpTtest, 2,as.numeric)
logFCmedianGrp1 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c(sCol:mCol)],na.rm=T)
logFCmedianGrp2 = matrixStats::rowMedians(dataSellog2grpTtestNum[,c((mCol+1):eCol)],na.rm=T)
logFCmedianGrp1[is.nan(logFCmedianGrp1)]=0
logFCmedianGrp2[is.nan(logFCmedianGrp2)]=0
logFCmedian = logFCmedianGrp1-logFCmedianGrp2
logFCmedianFC = 2^(logFCmedian+.Machine$double.xmin)
logFCmedianFC=squish(logFCmedianFC,c(0.01,100))
hist(logFCmedianFC)
log2FCmedianFC=log2(logFCmedianFC)
hdr<-gsub("[^[:alnum:] ]", "",inpF)
hist(log2FCmedianFC,main = hdr)
rowName<-paste(sapply(strsplit(paste(sapply(strsplit(rownames(dataSellog2grpTtest), ";"), "[", 1)), "-"), "[", 1))
ttest.results = data.frame(Uniprot=rowName,PValueMinusLog10=pValNAminusLog10,FoldChanglog2median=logFCmedianFC,CorrectedPValueBH=pValBHna,TtestPval=pValNA,dataSellog2grpTtest,Log2MedianChange=logFCmedian,RowGeneUniProtScorePeps=rownames(dataSellog2grpTtest))
writexl::write_xlsx(ttest.results,paste0(inpF,selection,sCol,eCol,hdr,"wTestBHgrpOut25pC.xlsx"))
#limma::vennDiagram(cbind(as.matrix(dataSellog2grpTtest[,c(sCol:mCol)]),as.matrix(dataSellog2grpTtest[,c((mCol+1):eCol)])))
limma::vennDiagram(cbind(logFCmedianGrp1,logFCmedianGrp2))
```


