#install.packages("BiocManager")
#BiocManager::install("limma")
#BiocManager::install("edgeR")
library(limma)
library(edgeR)
inpD<-"F:/seqRNA/"
countTable = read.table(paste0(inpD,"count.thread6.tsv"),header=TRUE,row.names=1)
colnames(countTable)
condition = factor( c("Mut","Mut","WT","Mut","WT","WT"))
des = model.matrix(~-1+condition)
colnames(des) = levels(condition)
cmat <- makeContrasts(WT - Mut, levels=des)
dge <- DGEList(counts=countTable)
dge <- calcNormFactors(dge)
v <- voom(dge,design=des)
fit <- lmFit(v,design=des)
fit <- contrasts.fit(fit, cmat)
fit <- eBayes(fit)
a <- decideTests(fit,adjust.method="fdr", p.value=0.05, lfc=0)
sma = summary(a)
dmm <- dim(countTable)
res <- topTable(fit,n=dmm[1],coef=1)
plot(res$logFC,-log10(res$adj.P.Val))
write.csv(res,file=paste0(inpD,"Voom_diffexp.csv"))
