#Rscript diffExprDEP.r
#BiocManager::install("DEP")
#BiocManager::install("MSnbase")#MsCoreUtils
library(DEP)
library(dplyr)
#inputAnnotation <-"L:/promec/Animesh/Mathilde/Groups.txt"
#annotation <- read.table(inputAnnotation,sep="\t",header=TRUE)
#annotation<-annotation[annotation$Rem!="Y",]
#annotationDep <- data.frame(label=paste0("X",gsub("[0-9]$","",annotation$Name,perl=T)),condition= annotation$Bio,replicate=annotation$Match)
#annotationDep <- data.frame(label=paste0("",gsub("","",annotation$Name,perl=T)),condition= annotation$Bio,replicate=annotation$Match)
#write.table(annotationDep, "L:/promec/Animesh/Mathilde/Groups.DEP.txt", row.names = FALSE,sep ="\t")
#annotationDep<-read.table("L:/promec/Animesh/Mathilde/Groups.DEP.txt", row.names = 1,sep ="\t", header = TRUE)
#DEP::run_app("LFQ")
pdf("L:/promec/Animesh/Mathilde/DEP.pdf")
data <- read.table("L:/promec/Animesh/Mathilde/rawdata_from animesh 2.txt", row.names = 1,sep ="\t", header = TRUE)#X99_Slot1.2_1_402
colnames(data)
data %>% group_by(Gene.names) %>% summarize(frequency = n()) %>% arrange(desc(frequency)) %>% filter(frequency > 1)
data_unique <- make_unique(data, "Gene.names", "Majority.protein.IDs", delim = ";")
data$name %>% duplicated() %>% any()
LFQ_columns <- grep("LFQ.", colnames(data_unique)) # get LFQ column numbe
experimental_design <- read.table("L:/promec/Animesh/Mathilde/Groups.DEP.txt",sep="\t",header=TRUE)#UbiLength_ExpDesign
data_se <- make_se(data_unique, LFQ_columns, experimental_design)
plot_frequency(data_se)
data_filt <- filter_missval(data_se, thr = 0)
plot_numbers(data_filt)
data_filt2 <- filter_missval(data_se, thr = 1)
plot_numbers(data_filt2)
plot_coverage(data_filt)
plot_coverage(data_filt2)
data_norm <- normalize_vsn(data_filt)
meanSdPlot(data_norm)
meanSdPlot(data_norm,rank=F)
plot_normalization(data_filt, data_norm)
data_norm_df<-data_norm@assays@data@listData[[1]]
boxplot(data_norm_df)
hist(data_norm_df)
countTableDAuniGORNAddsMed<-apply(data_norm_df,1,function(x) median(x,na.rm=T))
countTableDAuniGORNAddsSD<-apply(data_norm_df,1,function(x) sd(x,na.rm=T))
countTableDAuniGORNAdds<-(data_norm_df-countTableDAuniGORNAddsMed)#/countTableDAuniGORNAddsSD
hist(countTableDAuniGORNAdds)
par(mar=c(12,3,1,1))
boxplot(countTableDAuniGORNAdds,las=2)
write.csv(data_norm_df,"L:/promec/Animesh/Mathilde/rawdata_from animesh 2.DEP.csv",quote=FALSE)
dataLFQtdc<-cor(data_norm_df,use="pairwise.complete.obs",method="spearman")
pheatmap::pheatmap(dataLFQtdc)
data_norm2 <- normalize_vsn(data_filt2)
meanSdPlot(data_norm2)
meanSdPlot(data_norm2,rank=F)
plot_normalization(data_filt2, data_norm2)
plot_missval(data_filt)
plot_missval(data_filt2)
plot_detect(data_filt)
plot_detect(data_filt2)
#impute(data_norm, fun = "")
data_imp <- impute(data_norm, fun = "MinProb", q = 0.01)
data_imp_man <- impute(data_norm, fun = "man", shift = 1.8, scale = 0.3)
data_imp_knn <- impute(data_norm, fun = "knn", rowmax = 0.9)
plot_imputation(data_norm, data_imp)
plot_imputation(data_norm, data_imp_man)
plot_imputation(data_norm, data_imp_knn)
data_diff <- test_diff(data_imp_man, type = "control", control = "STNTC")
#data_diff_manual <- test_diff(data_imp, type = "manual", test = c("SI", "STNTC"))
dep <- add_rejections(data_diff, alpha = 0.05, lfc = log2(1.5))
plot_pca(dep, x = 1, y = 2, n = 500, point_size = 4)
plot_cor(dep, significant = TRUE, lower = 0, upper = 1, pal = "Reds")
plot_heatmap(dep, type = "centered")
plot_volcano(dep,contrast = "SI_vs_STNTC")
plot_single(dep, proteins = c("Fer", "Lamc2", "Lamb3", "Zswim6", "M", "2310057J18Rik", "Lamb2"),type = "centered")
plot_cond(dep)
data_results <- get_results(dep)
write.table(data_results, "L:/promec/Animesh/Mathilde/DEP_results.txt", row.names = FALSE,sep ="\t")
data_results %>% filter(significant) %>% nrow()
df_wide <- get_df_wide(dep)
write.table(df_wide, "L:/promec/Animesh/Mathilde/DEP_results_wide.txt", row.names = FALSE,sep ="\t")
