```{r data-xml}
install.packages("xml2")
library("xml2")
tt <- read_xml("F:/promec/Gygi/b1947_293T_proteinID_11B_QE3_122212.pep.xml")
xml_name(tt)
xml_children(tt)
```

```{r data-input}
tt <- "F:/promec/Gygi/b1947_293T_proteinID_11B_QE3_122212.pep.xml"
```

```{r pep-xml-read}
source("https://bioconductor.org/biocLite.R")
biocLite("pepXMLTab")
library("pepXMLTab")
tttt <- pepXML2tab(tt)
tttt[1,]
hist(as.numeric(tttt$massdiff))
```

```{r filter}
passed <- PSMfilter(tttt, pepFDR = 0.01, scorecolumn = 'spscore', hitrank = 1,minpeplen = 6, decoysuffix = '_REVERSED')
passed[1, ]
mdiff = as.numeric(passed$precursor_neutral_mass) - as.numeric(passed$calc_neutral_pep_mass)
dhist = hist(mdiff)
warnings()
hist(log10(dhist$density))
max(log10(dhist$density))

```



```{r de-gauss}
#https://cran.r-project.org/web/packages/mclust/vignettes/mclust.html
#library(mclust)
for(jmp in seq(from=0, to=500, by=25)){print(jmp)
jmp=480
data <- read.delim("F:/promec/Qexactive/LARS/2016/Andrea/2016 desember/161219_IP ugi 1D gel alle band/errtolPD21/161222_ip_ugi_band 2/161222_ip_ugi_band_PSMs.txt",sep="\t",header=T)
mdiff=data[data$Delta.mz.in.Da<(-jmp)|data$Delta.mz.in.Da>jmp,]$Delta.mz.in.Da
summary(mdiff)
hist(mdiff,breaks=1000)
mod4 = densityMclust(mdiff)
mod4$parameters$mean
summary(mod4)
plot(mod4, what = "BIC")
plot(mod4, what = "density")
plot(mod4, what = "diagnostic", type = "qq")
}

```



```{r write-output}
wtf = paste0(tt,"mu.txt")
write.table(mod4$parameters, wtf,sep = "\t")
```

```{r pwr}
install.packages("pwr")
library(pwr)
help(pwr)
pwr.p.test(h=0.2,n=60,sig.level=0.05,alternative="two.sided")
?pwr.t.test
pwr.t.test(d=0.5,n=NULL,sig.level=0.05,alternative=c("two.sided"),type="two.sample",power=0.8)


```



```{r data}
data=read.delim("C:/cygwin64/home/PROMECuser/ftp.pride.ebi.ac.uk/pride/data/archive/2016/01/PXD001582/130319_LINDA_K18.txt", skip=1, header=T)


```


```{r MZ, echo=FALSE}
plot(data$xcorr)
hist(data$xcorr)

```

```{r gauss}
s<-2
r<-1000
x<-seq(-r,r,s)
y<-exp(-x^2/(2*s^2))/(s*sqrt(2*pi))
hist(y)
plot(x,y)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r eda, echo=FALSE}
class(data)
attach(data)
plot(LFQ.intensity.H.70511_Magnar_HC_Ipsi_OGG1_02 ~ LFQ.intensity.L.70511_Magnar_HC_Ipsi_OGG1_01)
install.packages('mclust')
library(mclust)
densityMclust((LFQ.intensity.H.70511_Magnar_HC_Ipsi_OGG1_02))$parameters$mean
```

```


