---
#title: "Expression GO"
output: html_document
runtime: shiny
---

```{r data,echo=F}
lPep=100
nPep=10000
nTot=lPep*nPep
data<-runif(nTot)
#hist(sample(data,100000,replace=T),breaks=nPep)
sPep=rnorm(lPep)
n=1
i=1
while(n<=lPep){
  print(n)
  print(i)
  sPep[c(seq(n,n+i-1))]=sample(data,i,replace=T)
  n=n+i
  i=i+1
}
hist(sPep,breaks=lPep)

#install.packages('readxl')
library('readxl')
pathD<-"L:/promec/Animesh/Camilla"
inpF<-file.path(pathD,"Combo.xlsx WSRTun.xls")
data <- read_excel(inpF)
```

```{r euler,echo=F}
#install.packages('eulerr')
library(eulerr)
#euler(dataNorm<.5)$original.values
```

```{r ggdark,echo=F}
#install.packages("ggdark")
#library(ggdark)
#dark_theme_minimal()
```


```{r clusterProfiler, echo = FALSE}
#https://bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html
#BiocManager::install('clusterProfiler')
##source("https://bioconductor.org/biocLite.R")
##biocLite("BiocUpgrade") ## you may need this
##biocLite("clusterProfiler")
#biocLite("org.Hs.eg.db")
#install.packages('BiocManager')
#library('BiocManager')
#BiocManager::install("clusterProfiler")
#install.packages("colorspace")
#devtools::install_github('cran/colorspace')
#library("clusterProfiler")
#BiocManager::install("org.Hs.eg.db")
#library("org.Hs.eg.db")
#data$`Donor38 WSRT`
thresh=0.25
#dataSub=subset(data,`NB4 Biol Rep 22 WSRT`<=thresh & `MCCAR Biol Rep 25 WSRT`<=thresh & `Donor38 WSRT`<=thresh)[,1]
#Uniprot<-sapply(strsplit(subset(data,`NB4 Biol Rep 22 WSRT`<=thresh & `MCCAR Biol Rep 25 WSRT`<=thresh & `Donor38 WSRT`<=thresh)[,1],";"))
#Uniprot<-sapply(strsplit(dataSub$`T: Majority protein IDs`,";"), `[`, 1)
#enrichGO(gene=Uniprot,OrgDb=org.Hs.eg.db,keyType= 'UNIPROT',ont= "CC",pAdjustMethod = "BH",pvalueCutoff  = 0.01,qvalueCutoff  = 0.05)
#UniprotEG<-bitr(Uniprot, fromType="UNIPROT", toType="ENTREZID", OrgDb="org.Hs.eg.db")
#writeClipboard(UniprotEG$UNIPROT)
#UniprotKEGG<-bitr_kegg(Uniprot, fromType='uniprot', toType='kegg', organism='hsa')
#kk <- enrichKEGG(gene=UniprotEG$ENTREZID)
#head(kk@result[["Description"]])
#browseKEGG(kk,kk@result[["ID"]][1])
```

```{r shiny, echo = FALSE}
#https://rmarkdown.rstudio.com/authoring_shiny.html
#install.packages('shiny')
#ctrl-shift-K
#rmarkdown::run
#shiny::renderUI
library(shiny)
dN_shiny <- data[,3:5]
```

```{r slider, echo=FALSE}
inputPanel(
  sliderInput("pv", "#value:", min = 0, max = 1, value = 0.5),
  selectInput("expression", label = "Sample:",choices = colnames(dN_shiny), selected = colnames(dN_shiny)[1]))
  renderText({paste("Inputs:", input$pv,"\n",input$expression,"\n",euler(dN_shiny<=input$pv)$original.values[input$expression])})
```

```{r plot, echo = FALSE}
renderPlot({
  plot(euler(dN_shiny<=input$pv,shape="ellipse"),quantities=TRUE)
  })
```


