KEGG map with Gene symbols using Pathview
========================================================

```{r setup}
#rm(list = ls())
#detach("package:pathview", unload=TRUE)
getwd()
knitr::opts_knit$get("root.dir") 
```

```{r install libraries and setup}
source("http://bioconductor.org/biocLite.R")
biocLite('pathview')
biocLite('IRanges')
install.packages("RSQLite")
biocLite('XVector')
library(pathview)
?pathview
```



```{r cluster xlsx}
install.packages("readxl")
library(readxl)
#hda=read.table("BERmedianFilteredvalsPathExp.txt",row.names=1, header=T)
hda=read.table("Y:/felles/PROTEOMICS and XRAY/Ani/iPOND/BERmedianFilteredvalsPathExp.txt",row.names=1, header=T)
#hda=readxl::read_excel("Y:/felles/PROTEOMICS and XRAY/Articles in prep/Myeloma versus MGUS/MyelomaProjectB1B2combineTTpermcorr.xlsx")
#pathview(hda,pathway.id="hsa03410",gene.idtype="symbol",low = list(gene = "yellow"), mid = list(gene = "white"), high = list(gene = "orange"),bins = list(gene = 10),node.sum="sum", both.dirs=list(gene=T),limit=list(gene=1),na.col="transparent")
summary(hda)
pathview(hda,pathway.id="hsa03410",gene.idtype="symbol")
heatmap(as.matrix(hda$averageLog2diffMMtoMGUS))
hist(as.matrix(hda$averageLog2diffMMtoMGUS))
pdf(file="plot.pdf")
plot(hda)
dev.off()
time()
install.packages("devtools")
library(devtools)
install.packages("ggplot2")
library(ggplot2)
install.packages("sp")
library(sp)
install_github("hadley/dplyr")
install_github("twitter/AnomalyDetection")
install_github("yunzhang813/FUNNEL-GSEA-R-Package")
library("FUNNEL")
FUNNEL::FUNNEL.GSEA(hda)
```


```{r BER}
hda=readExpData("Y:/felles/PROTEOMICS and XRAY/Ani/iPOND/BERmedianFilteredvalsPathExp.txt",row.names=1)
library(pathview)
hda=read.table("BERmedianFilteredvalsPathExp.txt",row.names=1, header=T)
hda=read.table("Y:/felles/PROTEOMICS and XRAY/Ani/iPOND/BERmedianFilteredvalsPathExp.txt",row.names=1, header=T)
hda[,1:3]
=as.matrix(hda)
#pathview(hda,pathway.id="hsa03410",gene.idtype="symbol",low = list(gene = "yellow"), mid = list(gene = "white"), high = list(gene = "orange"),bins = list(gene = 10),node.sum="sum", both.dirs=list(gene=T),limit=list(gene=1),na.col="transparent")
pathview(hda,pathway.id="hsa03410",gene.idtype="symbol")
heatmap(as.matrix(hda))
pdf(file="plot.pdf")
plot(hda)
dev.off()
time()
```

