source("http://bioconductor.org/biocLite.R")
biocLite("clusterProfiler")
library("clusterProfiler")
data(gcSample)
x <- groupGO(gene=gcSample[[1]],organism="human",ont="CC",level=2,readable=TRUE)
head(summary(x))
x
id=read.table("ListOfTWLUniprotNIFEIDtsv.txt")
x <- groupGO(gene=(as.character(as.matrix(id))),organism="human",ont="CC",level=4,readable=TRUE)
head(summary(x))
x <- groupGO(gene=(as.character(as.matrix(id))),organism="human",ont="CC",level=4,readable=TRUE)
head(summary(x))
page(summary(x))
plot(x)
