protmut='GAMGQLKPMEINPEMLNKVLSRLGVAGQWRFVDVLGLEEESLGSVPAPACALLLLFPLTAQHENFRKKQIEELKGQEVSPKVYFMKQTIGNSCGTIGLIHAVANNQDKLGFEDGSVLKQFLSETEKMSPEDRAKCFEKNEAIQAAHDAVAQEGQCRVDDKVNFHFILFNNVDGHLYELDGQMPFPVNHGASSEDTLLKDAAKVCREFTEREQGEVRFSAVALCKAA'
protwt='GAMGQLKPMEINPEMLNKVLSRLGVAGQWRFVDVLGLEEESLGSVPAPACALLLLFPLTAQHENFRKKQIEELKGQEVSPKVYFMKQTIGNSCGTIGLIHAVANNQDKLGFEDGSVLKQFLSETEKMSPEDRAKCFEKNEAIQAAHDAVAQEGQCRVDDKVNFHFILFNNVDGHLYELDGRMPFPVNHGASSEDTLLKDAAKVCREFTEREQGEVRFSAVALCKAA'



enz='PEPS'

enz='ASP-N'
[pepwt pepwtpos pepwtlen pepwtmc]=cleave(protwt,enz)
[pepmut pepmutpos pepmutlen pepmutmc]=cleave(protmut,enz)
plot(pepwtlen,pepwtlen,'r.')
molweight(cell2mat(pepwt(10)))
molweight(cell2mat(pepmut(10)))


molweight(cell2mat(pepwt(45)))
molweight(cell2mat(pepmut(2)))



