Starting job 5413366 on c3-20 at Thu Mar 31 13:48:33 CEST 2022

we are running from this directory: /cluster/projects/nn9036k/scripts
 the name of the job is: MQ40
Th job ID is 5413366
The job was run on these nodes: c3-20
Number of nodes: 1
We are using 40 cores
We are using 40 cores per node
Total of 4 cores
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) StdEnv
Mono JIT compiler version 6.8.0.105 (tarball Fri Oct  9 11:00:40 CEST 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
3.1.300
Configuring 
Assemble run info 
Finish run info 
Testing fasta files 
Testing raw files 
Feature detection TIMS 
