NEWBLER = read.table('NEWBLER10x')
MIRA = read.table('MIRAAn')
PHRAP = read.table('PHRAPAn')
CAP3 = read.table('CAP3An')
par(mfrow = c(2,2))
hist(PHRAP$V3, xlab = "Contig Length",ylab = "Number of Contig (s)", col="cyan", border="black", main = "PHRAP", breaks=10,xlim=c(0,5000), ylim=c(0,5000))
hist(CAP3$V3, xlab = "Contig Length",ylab = "Number of Contig (s)", col="magenta", border="black", main = "CAP3", breaks=10,xlim=c(0,5000), ylim=c(0,5000))
hist(MIRA$V3, xlab = "Contig Length",ylab = "Number of Contig (s)", col="orange", border="black", main = "MIRA", breaks=10,xlim=c(0,5000), ylim=c(0,5000))
hist(NEWBLER$V3, xlab = "Contig Length",ylab = "Number of Contig (s)", col="gold", border="black", main = "NEWBLER", breaks=10,xlim=c(0,5000), ylim=c(0,5000))

