reads = bnp.open('F:/tk/TK9_1_22FFLLLT3_AGAGAACCTA-GGTTATGCTA_L005__1.fq.gz').read()
print(reads)
collectReads = bnp.open('Z:/Download/rnafusion/data/fastq/SRR31089076_1.fastq.gz').read()
print(reads)
gc_content = np.mean((reads.sequence == "C") | (reads.sequence == "G"))
print(gc_content)
