```{r proteinGroups}
#inpD<-"F:\promec\Qexactive\LARS\2020\mars\Heidi nano\combined\txt"
inpD <-paste0(getwd(),"/Heidi/")
inpF<-paste0(inpD,"proteinGroups.txt")
data <- read.delim(inpF,sep="\t",header = T,row.names = 1)
#clean
data = data[!data$Reverse=="+",]
#data = data[!data$C..Potential.contaminant=="+",]
row.names(data)<-paste(row.names(data),data$Gene.names,data$Protein.names,sep=";;")
summary(data)
dim(data)
selection<-"LFQ.intensity"
LFQ<-as.matrix(data[,grep(selection,colnames(data))])
protNum<-1:ncol(LFQ)
colnames(LFQ)=paste(protNum,sub(selection,"",colnames(LFQ)),protNum,sep="_")
dim(LFQ)
log2LFQ<-log2(LFQ)
log2LFQ[log2LFQ==-Inf]=NA
log2LFQ[log2LFQ==0]=NA
summary(log2LFQ)
```

```{r heatmap-col-cor}
hda<-log2LFQ
protNum<-1:nrow(hda)
gen<-gsub("^(.*?);.*", "\\1",data$Gene.names)
gen<-paste(sapply(gen, "[", 1))
row.names(hda)<-paste0(protNum,gen)
hdaC<-cor(hda,use="pairwise.complete.obs")
row.names(hdaC)<-colnames(hdaC)
#install.packages("pheatmap")
svgPHC<-pheatmap::pheatmap(hdaC)
#install.packages("ggplot2")
#install.packages("svglite")
cn<-paste(gsub("[^[:alnum:] ]", "",inpD), collapse='_' )
ggplot2::ggsave(file=paste0(inpD,selection,cn,"ColCorClusterPlot.svg"),plot=svgPHC) 
```

```{r heatmap-generow}
#hda<-log2LFQ
hda<-log2LFQ[,c(1:25,27,29:ncol(log2LFQ))]
protNum<-1:nrow(hda)
gen<-gsub("^(.*?);.*", "\\1",data$Gene.names)
gen<-paste(sapply(gen, "[", 1))
row.names(hda)<-paste(gen,protNum,sep=";")
hda[is.na(hda)]=0
svgPHC<-pheatmap::pheatmap(hda,fontsize_row=1,fontsize_col=5)#,scale="row",clustering_distance_rows = "euclidean",clustering_distance_cols = "euclidean",annotation_col = label,fontsize_row=5,fontsize_col=5)
ggplot2::ggsave(file=paste0(inpD,selection,cn,"GeneRowColClusterPlot.svg"),plot=svgPHC) 
```


```{r heatmap}
#BiocManager::install("ComplexHeatmap")
#library(ComplexHeatmap)
ComplexHeatmap::Heatmap(hdaC)
```

```{r label}
inpL<-paste0(inpD,"Groups.txt")
label<-read.table(inpL,header=T,row.names=1,sep="\t")#, colClasses=c(rep("factor",3)))
summary(label)
rownames(label)<-label[['Name']]
rownames(label)
rownames(groups)<-sub("-","\\.",rownames(groups))
groups$rows<-rownames(groups)
summary(groups)
groupsT<-as.data.frame(groups[,grep("Type$",colnames(groups))])
rownames(groupsT)<-rownames(groups)
colnames(groupsT)<-"Bead"
groupsR<-as.matrix(groupsT[,-grep("Bio",colnames(groupsT))])
rownames(groupsR)<-rownames(groupsT)
groupsC<-as.matrix(groupsT[,grep("Bio",colnames(groupsT))])
rownames(groupsC)<-rownames(groups)
groupsD<-as.matrix(groups[,12])
groupsD[groupsD[,1]=="",]<-"OK"
rownames(groupsD)<-rownames(groups)
#svgPHC<-pheatmap::pheatmap(hdaC,fontsize_row=6,annotation_row=groupsR)
```

```{r heatmap-sample-correlation}
#BiocManager::install("ComplexHeatmap")
#library(ComplexHeatmap)
hd<-log2LFQ
colnames(hd)
selection<-"LFQ.intensity.60313_AnneMari_"
colnames(hd)<-sub(selection,"",colnames(hd))
colnames(hd)
#PLE, PLT, PKE, PKT unlist(groups[(groups$Type=="PLE")&(!is.na(groups$Type)),1])
#hda<-hd[,unlist(groups[(groups$Type=="PLE")|(groups$Type=="PLT")|(groups$Type=="PKE")|(groups$Type=="PKT"),13])]
cn<-c(groups[(groups$Type=="PLE")|(groups$Type=="PLT")|(groups$Type=="PKE")|(groups$Type=="PKT"),13])
hda<-hd[,!(colnames(hd) %in% cn)]
#hda[is.na(hda)]=0
protNum<-1:nrow(hda)
row.names(hda)<-paste0(protNum,gen)
#dist(t(hda))
#hdaC<-cor(hda,use="pairwise.complete.obs")
hdaC<-dist(t(hda),method="euclidean")
hdaC[is.na(hdaC)]=0
svgPHC<-pheatmap::pheatmap(hdaC,fontsize_row=5,fontsize_col=5,annotation_row=groupsT,annotation_col=groupsT)
#svgPHC<-pheatmap::pheatmap(hdaC,fontsize_row=5,fontsize_col=5,annotation_row=groupsD,annotation_col=groupsD)
library(ggplot2)
cn<-paste(gsub("[^[:alnum:] ]", "",cn), collapse='_' )
ggsave(file=paste0(inpD,selection,"NOT",cn,"clusterPlot.svg"),plot=svgPHC) 
ComplexHeatmap::Heatmap(hdaC)
```

```{r data}
inpF<-"L:/promec/Animesh/Lymphoma/Sel66.txt"
data<-read.table(inpF,header=T,sep="\t",row.names = 1)
summary(data)
```

```{r label-gene}
inpL<-paste0(inpD,"New z-score heatmaps - 11.05.2020.xlsx")
label<-read_xlsx(inpL)#read.table(inpL,header=T,row.names=1,sep="\t")#, colClasses=c(rep("factor",3)))
#colnames(label)=sub("\\-[0-9]+","",colnames(label))
#colnames(label)
summary(label)
colnames(label)=sub("\\-[0-9]+","",colnames(label))
colnames(label)
rownames(label)<-label[['Name']]
rownames(label)
summary(label)
```

```{r heatmap}
#install.packages('pheatmap')
library(pheatmap)
y<-as.matrix(data[1:35])
summary(y)
pheatmap(y,scale="row")
y[is.na(y)]<-0
pheatmap(y,scale="column",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation")
colnames(y)=sub("X","",colnames(y))
y<-y[,rownames(label)]
svgPHC<-pheatmap(y,scale="row",clustering_distance_rows = "euclidean",clustering_distance_cols = "euclidean",annotation_col = label,fontsize_row=5,fontsize_col=5)
library(ggplot2)
ggsave(file=paste0(inpF,"clusterPlot.svg"),plot=svgPHC)
```

```{r scale}
#install.packages('quantable')
library(quantable)
y<-data[1:35]
y=robustscale(y)
y$data[is.na(y$data)]<-0
names(y$data)=sub("X","",names(y$data))
pheatmap(y$data,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6)
pheatmap(y$data,scale="row",clustering_distance_rows = "manhattan",clustering_distance_cols = "manhattan",fontsize_row=6,annotation_col = label)
```


```{r write}
install.packages('dplyr')
library(dplyr)
colnames(y$data)
yy<-rbind(y$data,label$Code)
pheatmap(yy,scale="row",clustering_distance_rows = "correlation",clustering_distance_cols = "correlation",fontsize_row=6)
yy<-t(yy)
write.csv(y$data,"data.csv")
```

