```{r data}
inpF <-"L:/Animesh/Zahoor/CoMMpass_IA8b.txt"
dataG <- read.delim(inpF,row.names=1,sep="\t",header = T)
summary(data)
factorS=names(data)[grep("MMRF", names(data))]
#plot(data)
```

```{r condition}
library(survival)
#library(cmprsk)
inpC <-"L:/Animesh/Zahoor/Compass_Survival.txt"
dataC <- read.delim(inpC,row.names=1,sep="\t",header = T)
factor(dataC$censpfs)
summary(factor(dataC$censpfs))
factorC=rownames(data)[grep("MMRF", names(data))]
#plot(data)
```

```{r test}
pairwise.t.test(c(rnorm(100),rnorm(100)))
rank(chk)
?pairwise.t.test
chk=rep(chk,100)
summary(chk)
?reshape
?rep
dim(chk)
plot(chk)

n <- 1e5
k <- 20
d <- data.frame(y = rnorm(n*k), x = rnorm(n*k), set = rep(1:k, each = n))
fit_lm <- function(data, set_id) {
data=data[set_id]
lm(y ~ x, data = .)
}

system.time(fit_lm(d, 1))
```

```{r survival}
dataNorm=log2(dataG[,grep("MMRF", names(dataG))]+1)
dataNorm=dataG[,grep("MMRF", names(dataG))]
summary(dataNorm$MMRF_1021)
hist(dataNorm$MMRF_1021)
dataNorm=dataNorm[ , order(colnames(dataNorm))]
dataC=dataC[order(row.names(dataC)), ]
coxPHm <- matrix(NA, nrow=nrow(dataNorm), ncol=2)
for (i in 1:nrow(dataNorm)) {
  coxPHm[i,1] = row.names(dataNorm[i,])
  coxPHm[i,2] = coef(summary(coxph(Surv(dataC$ttcpfs, dataC$censpfs) ~ . , data.frame(t(dataNorm[i,])))))[,5]
}
coxPHm <- cbind(coxPHm,p.adjust(coxPHm[,2],method = "fdr"))
resEfsByDis <- coef(summary(coxph(Surv(dataC$ttcpfs, dataC$censpfs) ~ . , data.frame(t(dataNorm[2,])))))[,5]

                       type      = "kaplan-meier"
                       error     = "greenwood"
                       conf.type = "log-log"
                    
coef(summary(resEfsByDis))[,5]
```
```{r check}
plot(as.numeric(log2(dataNorm["ENSG00000223970",])),dataC$ttcpfs,col=factor(dataC$censpfs)) # common
plot(as.numeric(log2(dataNorm["ENSG00000104499",])),dataC$ttcpfs,col=factor(dataC$censpfs))
plot(as.numeric(log2(dataNorm["ENSG00000228465",])),dataC$ttcpfs,col=factor(dataC$censpfs))
plot(as.numeric(log2(dataNorm["ENSG00000184185",])),dataC$ttcpfs,col=factor(dataC$censpfs))
plot(as.numeric((dataNorm["ENSG00000118407",])),dataC$ttcpfs,col=factor(dataC$censpfs)) # diverge from log2 results
```


```{r write}
outF = paste0(inpF,"coxPHsortNoLog2.txt")
write.table((coxPHm),outF,sep="\t")
```
